/**
 * Curated starter shortlist of real colleges per (city, college category), keyed by category
 * name. Shared by the manual `seed:colleges` script and the auto-seed run at server startup
 * (see collegeService.ensureCollegesSeeded) so both stay in sync with one source of truth.
 *
 * Complete national systems (all 23 IITs, all 31 NITs, all 20 IIMs, every operational AIIMS, VIT's
 * Vellore/Chennai/AP/Bhopal campuses) are enumerated in full here, even where a campus sits in a
 * small town — students search by the brand name, not city size. `indianCities.ts` gained a
 * handful of smaller towns (Ropar, Mandi, Palakkad, Goa, Rohtak, Kashipur, Rishikesh, Deoghar,
 * Raebareli, Karaikal) specifically so those campuses' actual city has a matching City record; a
 * few campuses in towns still not worth cataloguing as a full city (e.g. NIT Andhra Pradesh at
 * Tadepalligudem, IIM Sirmaur) are filed under the nearest catalogued city instead. Beyond the
 * named national systems this stays a curated shortlist, not an exhaustive directory of every
 * college in India — the picker always offers an "Other" fallback for anything missing, and
 * admins can add more colleges for other cities from the admin panel at any time.
 *
 * `nirfRank` is only set where a college's #1 spot in its NIRF category ranking has been
 * essentially unchanged for years (the seven oldest IITs in Engineering, AIIMS Delhi in
 * Medical, NLSIU Bangalore in Law, IARI Delhi in Agriculture) — everything else is ordered via
 * `sortOrder` by general reputation instead of a claimed exact rank, to avoid asserting NIRF
 * numbers this data can't guarantee are current. Categories NIRF doesn't rank as a discipline
 * of its own (Design, Commerce, Science, Arts, Animation, Hotel Management) are sortOrder-only
 * throughout, and include well-known institutions outside the NIRF list entirely (e.g. NIFT,
 * which NIRF doesn't rank) alongside NIRF-listed ones, since the goal is "colleges students
 * actually apply to," not "colleges NIRF ranks."
 */

export type SeedCollege = { city: string; name: string; nirfRank?: number; sortOrder?: number };

export const ENGINEERING_COLLEGE_SEEDS: SeedCollege[] = [
  // The seven oldest IITs — stable relative NIRF Engineering order.
  { city: "Chennai", name: "IIT Madras", nirfRank: 1 },
  { city: "Delhi", name: "IIT Delhi", nirfRank: 2 },
  { city: "Mumbai", name: "IIT Bombay", nirfRank: 3 },
  { city: "Kanpur", name: "IIT Kanpur", nirfRank: 4 },
  { city: "Kharagpur", name: "IIT Kharagpur", nirfRank: 5 },
  { city: "Roorkee", name: "IIT Roorkee", nirfRank: 6 },
  { city: "Guwahati", name: "IIT Guwahati", nirfRank: 7 },

  // Other well-known institutes, curated order (no asserted NIRF number).
  { city: "Hyderabad", name: "IIT Hyderabad", sortOrder: 1 },
  { city: "Varanasi", name: "IIT (BHU) Varanasi", sortOrder: 1 },
  { city: "Indore", name: "IIT Indore", sortOrder: 1 },
  { city: "Dhanbad", name: "Indian Institute of Technology (Indian School of Mines), Dhanbad", sortOrder: 1 },
  { city: "Bhubaneswar", name: "IIT Bhubaneswar", sortOrder: 2 },
  { city: "Gandhinagar", name: "IIT Gandhinagar", sortOrder: 2 },
  { city: "Jodhpur", name: "IIT Jodhpur", sortOrder: 2 },
  { city: "Patna", name: "IIT Patna", sortOrder: 2 },
  { city: "Tirupati", name: "IIT Tirupati", sortOrder: 2 },
  { city: "Bhilai", name: "IIT Bhilai", sortOrder: 2 },
  { city: "Jammu", name: "IIT Jammu", sortOrder: 2 },
  { city: "Dharwad", name: "IIT Dharwad", sortOrder: 2 },
  { city: "Goa", name: "IIT Goa", sortOrder: 2 },
  { city: "Ropar", name: "IIT Ropar", sortOrder: 2 },
  { city: "Mandi", name: "IIT Mandi", sortOrder: 2 },
  { city: "Palakkad", name: "IIT Palakkad", sortOrder: 2 },

  { city: "Mumbai", name: "Institute of Chemical Technology (ICT)", sortOrder: 10 },
  { city: "Mumbai", name: "Veermata Jijabai Technological Institute (VJTI)", sortOrder: 20 },
  { city: "Mumbai", name: "Sardar Patel Institute of Technology (SPIT)", sortOrder: 30 },
  { city: "Mumbai", name: "K J Somaiya College of Engineering", sortOrder: 40 },
  { city: "Mumbai", name: "Sardar Patel College of Engineering", sortOrder: 50 },

  { city: "Delhi", name: "Delhi Technological University (DTU)", sortOrder: 10 },
  { city: "Delhi", name: "Netaji Subhas University of Technology (NSUT)", sortOrder: 20 },
  { city: "Delhi", name: "Indraprastha Institute of Information Technology Delhi (IIIT-Delhi)", sortOrder: 30 },
  { city: "Delhi", name: "Jamia Millia Islamia — Faculty of Engineering and Technology", sortOrder: 40 },

  { city: "Bengaluru", name: "Indian Institute of Science (IISc) Bengaluru", sortOrder: 5 },
  { city: "Bengaluru", name: "RV College of Engineering", sortOrder: 10 },
  { city: "Bengaluru", name: "BMS College of Engineering", sortOrder: 20 },
  { city: "Bengaluru", name: "PES University", sortOrder: 30 },
  { city: "Bengaluru", name: "M S Ramaiah Institute of Technology", sortOrder: 40 },

  { city: "Chennai", name: "Anna University (CEG Campus)", sortOrder: 10 },
  { city: "Chennai", name: "SSN College of Engineering", sortOrder: 20 },
  { city: "Chennai", name: "VIT Chennai", sortOrder: 30 },
  { city: "Chennai", name: "SRM Institute of Science and Technology, Chennai", sortOrder: 40 },

  { city: "Pune", name: "College of Engineering Pune (COEP Technological University)", sortOrder: 10 },
  { city: "Pune", name: "Pune Institute of Computer Technology (PICT)", sortOrder: 20 },
  { city: "Pune", name: "Vishwakarma Institute of Technology", sortOrder: 30 },
  { city: "Pune", name: "MIT World Peace University", sortOrder: 40 },

  { city: "Hyderabad", name: "BITS Pilani Hyderabad Campus", sortOrder: 10 },
  { city: "Hyderabad", name: "International Institute of Information Technology, Hyderabad (IIIT-H)", sortOrder: 20 },
  { city: "Hyderabad", name: "Osmania University College of Engineering", sortOrder: 30 },

  { city: "Kolkata", name: "Jadavpur University", sortOrder: 10 },
  { city: "Kolkata", name: "Indian Institute of Engineering Science and Technology (IIEST), Shibpur", sortOrder: 20 },
  { city: "Kolkata", name: "Heritage Institute of Technology", sortOrder: 30 },

  { city: "Tiruchirappalli", name: "NIT Tiruchirappalli", sortOrder: 5 },
  { city: "Warangal", name: "NIT Warangal", sortOrder: 5 },
  { city: "Mangaluru", name: "NIT Surathkal", sortOrder: 5 },
  { city: "Kozhikode", name: "NIT Calicut", sortOrder: 5 },
  { city: "Jaipur", name: "Malaviya National Institute of Technology (MNIT) Jaipur", sortOrder: 5 },
  { city: "Surat", name: "Sardar Vallabhbhai National Institute of Technology (SVNIT)", sortOrder: 5 },
  { city: "Nagpur", name: "Visvesvaraya National Institute of Technology (VNIT)", sortOrder: 5 },
  { city: "Bhopal", name: "Maulana Azad National Institute of Technology (MANIT)", sortOrder: 5 },
  { city: "Rourkela", name: "NIT Rourkela", sortOrder: 5 },
  { city: "Prayagraj", name: "Motilal Nehru National Institute of Technology (MNNIT) Allahabad", sortOrder: 5 },
  { city: "Agartala", name: "NIT Agartala", sortOrder: 10 },
  { city: "Delhi", name: "NIT Delhi", sortOrder: 10 },
  { city: "Durgapur", name: "NIT Durgapur", sortOrder: 10 },
  { city: "Goa", name: "NIT Goa", sortOrder: 10 },
  { city: "Hamirpur", name: "NIT Hamirpur", sortOrder: 10 },
  { city: "Jalandhar", name: "NIT Jalandhar", sortOrder: 10 },
  { city: "Jamshedpur", name: "NIT Jamshedpur", sortOrder: 10 },
  { city: "Kurukshetra", name: "NIT Kurukshetra", sortOrder: 10 },
  { city: "Imphal", name: "NIT Manipur", sortOrder: 10 },
  { city: "Shillong", name: "NIT Meghalaya", sortOrder: 10 },
  { city: "Aizawl", name: "NIT Mizoram", sortOrder: 10 },
  { city: "Dimapur", name: "NIT Nagaland", sortOrder: 10 },
  { city: "Patna", name: "NIT Patna", sortOrder: 10 },
  { city: "Puducherry", name: "NIT Puducherry", sortOrder: 10 },
  { city: "Raipur", name: "NIT Raipur", sortOrder: 10 },
  { city: "Silchar", name: "NIT Silchar", sortOrder: 10 },
  { city: "Srinagar", name: "NIT Srinagar (J&K)", sortOrder: 10 },
  { city: "Srinagar", name: "NIT Uttarakhand (Srinagar, Garhwal)", sortOrder: 20 },
  { city: "Gangtok", name: "NIT Sikkim", sortOrder: 10 },
  { city: "Eluru", name: "NIT Andhra Pradesh", sortOrder: 10 },
  { city: "Itanagar", name: "NIT Arunachal Pradesh", sortOrder: 10 },

  { city: "Vellore", name: "Vellore Institute of Technology (VIT)", sortOrder: 10 },
  { city: "Amaravati", name: "VIT-AP University", sortOrder: 10 },
  { city: "Bhopal", name: "VIT Bhopal University", sortOrder: 15 },
  { city: "Coimbatore", name: "Amrita Vishwa Vidyapeetham, Coimbatore", sortOrder: 10 },
  { city: "Coimbatore", name: "PSG College of Technology", sortOrder: 20 },
  { city: "Thanjavur", name: "SASTRA Deemed University", sortOrder: 5 },
  { city: "Patiala", name: "Thapar Institute of Engineering and Technology", sortOrder: 5 },
  { city: "Manipal", name: "Manipal Institute of Technology (MIT)", sortOrder: 5 },
  { city: "Bhubaneswar", name: "Kalinga Institute of Industrial Technology (KIIT)", sortOrder: 10 },
  { city: "Bhubaneswar", name: "Siksha 'O' Anusandhan (SOA) University", sortOrder: 20 },
  { city: "Dehradun", name: "University of Petroleum and Energy Studies (UPES)", sortOrder: 10 },

  { city: "Ahmedabad", name: "Nirma University — Institute of Technology", sortOrder: 10 },
  { city: "Ahmedabad", name: "L D College of Engineering", sortOrder: 20 },

  { city: "Nagpur", name: "G H Raisoni College of Engineering", sortOrder: 20 },
  { city: "Nagpur", name: "Yeshwantrao Chavan College of Engineering (YCCE)", sortOrder: 30 },
  { city: "Nagpur", name: "Shri Ramdeobaba College of Engineering and Management (RBU)", sortOrder: 40 },
  { city: "Indore", name: "Shri Govindram Seksaria Institute of Technology and Science (SGSITS)", sortOrder: 10 },
  { city: "Indore", name: "Devi Ahilya Vishwavidyalaya (DAVV) — Institute of Engineering and Technology", sortOrder: 20 },
  { city: "Lucknow", name: "Institute of Engineering and Technology (IET), Lucknow", sortOrder: 10 },
  { city: "Lucknow", name: "Babu Banarasi Das National Institute of Technology and Management (BBDNITM)", sortOrder: 20 },
  { city: "Jaipur", name: "LNM Institute of Information Technology (LNMIIT)", sortOrder: 10 },
  { city: "Jaipur", name: "Manipal University Jaipur", sortOrder: 20 },
  { city: "Jaipur", name: "JECRC University", sortOrder: 30 },
  { city: "Coimbatore", name: "Kumaraguru College of Technology (KCT)", sortOrder: 30 },
  { city: "Coimbatore", name: "Coimbatore Institute of Technology (CIT)", sortOrder: 40 },
  { city: "Chandigarh", name: "Punjab Engineering College (PEC)", sortOrder: 10 },
  { city: "Chandigarh", name: "UIET, Panjab University", sortOrder: 20 },
  { city: "Bhopal", name: "Lakshmi Narain College of Technology (LNCT)", sortOrder: 20 },
  { city: "Kanpur", name: "Harcourt Butler Technical University (HBTU)", sortOrder: 10 },
  { city: "Vadodara", name: "Faculty of Technology and Engineering, The Maharaja Sayajirao University of Baroda", sortOrder: 10 },
  { city: "Nashik", name: "K K Wagh Institute of Engineering Education and Research", sortOrder: 10 },
  { city: "Guwahati", name: "Assam Engineering College", sortOrder: 10 },
  { city: "Bhubaneswar", name: "International Institute of Information Technology, Bhubaneswar (IIIT-Bh)", sortOrder: 30 },
  { city: "Bhubaneswar", name: "C V Raman Global University", sortOrder: 40 },
  { city: "Thiruvananthapuram", name: "College of Engineering Trivandrum (CET)", sortOrder: 10 },
  { city: "Visakhapatnam", name: "Andhra University College of Engineering", sortOrder: 10 },
  { city: "Visakhapatnam", name: "GITAM Institute of Technology", sortOrder: 20 },
  { city: "Ludhiana", name: "Guru Nanak Dev Engineering College (GNDEC)", sortOrder: 10 },
  { city: "Surat", name: "Sarvajanik College of Engineering and Technology (SCET)", sortOrder: 10 },
  { city: "Surat", name: "Government Engineering College (GEC), Surat", sortOrder: 20 },

  { city: "Agra", name: "Dayalbagh Educational Institute (DEI)", sortOrder: 10 },
  { city: "Ajmer", name: "Government Mahila Engineering College, Ajmer", sortOrder: 10 },
  { city: "Alappuzha", name: "College of Engineering, Cherthala", sortOrder: 10 },
  { city: "Aligarh", name: "Zakir Husain College of Engineering and Technology (AMU)", sortOrder: 10 },
  { city: "Alipurduar", name: "Alipurduar Government Engineering and Management College", sortOrder: 10 },
  { city: "Alwar", name: "Rajiv Gandhi Government Engineering College, Alwar", sortOrder: 10 },
  { city: "Ambala", name: "Maharishi Markandeshwar (Deemed to be University), Mullana", sortOrder: 10 },
  { city: "Ambikapur", name: "Vishwavidyalaya Engineering College (VEC), Ambikapur", sortOrder: 10 },
  { city: "Amravati", name: "Government College of Engineering, Amravati", sortOrder: 10 },
  { city: "Anantapur", name: "JNTUA College of Engineering, Anantapur", sortOrder: 10 },
  { city: "Angul", name: "Adarsha College of Engineering, Angul", sortOrder: 10 },
  { city: "Ara", name: "Government Engineering College, Bhojpur", sortOrder: 10 },
  { city: "Asansol", name: "Asansol Engineering College", sortOrder: 10 },
  { city: "Aurangabad", name: "Government College of Engineering, Aurangabad (GECA)", sortOrder: 10 },
  { city: "Aurangabad", name: "Deogiri Institute of Engineering and Management Studies", sortOrder: 20 },
  { city: "Balasore", name: "Balasore College of Engineering and Technology (BCET)", sortOrder: 10 },
  { city: "Ballari", name: "Ballari Institute of Technology and Management (BITM)", sortOrder: 10 },
  { city: "Bareilly", name: "SRMS College of Engineering, Technology and Research", sortOrder: 10 },
  { city: "Belagavi", name: "KLS Gogte Institute of Technology (GIT)", sortOrder: 10 },
  { city: "Berhampur", name: "NIST University, Berhampur", sortOrder: 10 },
  { city: "Bhagalpur", name: "Bhagalpur College of Engineering (BCE)", sortOrder: 10 },
  { city: "Bhagalpur", name: "Indian Institute of Information Technology (IIIT) Bhagalpur", sortOrder: 20 },
  { city: "Bharatpur", name: "Government Engineering College, Bharatpur", sortOrder: 10 },

  { city: "Bharuch", name: "Government Engineering College, Bharuch", sortOrder: 10 },
  { city: "Bhavnagar", name: "Shantilal Shah Engineering College, Bhavnagar", sortOrder: 10 },
  { city: "Bhiwadi", name: "Bhiwadi College of Polytechnic, Bhiwadi", sortOrder: 10 },
  { city: "Bhuj", name: "Government Engineering College, Bhuj", sortOrder: 10 },
  { city: "Bidar", name: "Guru Nanak Dev Engineering College, Bidar", sortOrder: 10 },
  { city: "Bikaner", name: "Engineering College Bikaner", sortOrder: 10 },
  { city: "Bokaro", name: "Guru Gobind Singh Educational Society's Technical Campus, Bokaro", sortOrder: 10 },
  { city: "Bulandshahr", name: "Marathwada Institute of Technology, Bulandshahr", sortOrder: 10 },
  { city: "Cuttack", name: "Bhubanananda Odisha School of Engineering, Cuttack", sortOrder: 10 },
  { city: "Dibrugarh", name: "Dibrugarh University Institute of Engineering and Technology", sortOrder: 10 },
  { city: "Durg", name: "Chhattisgarh Engineering College, Durg", sortOrder: 10 },
  { city: "Erode", name: "Kongu Engineering College, Erode", sortOrder: 10 },
  { city: "Erode", name: "Erode Sengunthar Engineering College, Erode", sortOrder: 20 },
  { city: "Faridabad", name: "J.C. Bose University of Science and Technology, YMCA, Faridabad", sortOrder: 10 },
  { city: "Faridabad", name: "Manav Rachna College of Engineering, Faridabad", sortOrder: 20 },
  { city: "Ghaziabad", name: "Ajay Kumar Garg Engineering College, Ghaziabad", sortOrder: 10 },
  { city: "Ghaziabad", name: "KIET Group of Institutions, Ghaziabad", sortOrder: 20 },
  { city: "Ghaziabad", name: "Raj Kumar Goel Institute of Technology, Ghaziabad", sortOrder: 30 },
  { city: "Greater Noida", name: "Sharda University, Greater Noida", sortOrder: 10 },
  { city: "Greater Noida", name: "Galgotias University, Greater Noida", sortOrder: 20 },
  { city: "Greater Noida", name: "Bennett University, Greater Noida", sortOrder: 30 },
  { city: "Gwalior", name: "Madhav Institute of Technology and Science, Gwalior", sortOrder: 10 },
  { city: "Haldwani", name: "Graphic Era Hill University, Haldwani Campus", sortOrder: 10 },
  { city: "Hosur", name: "Adhiyamaan College of Engineering, Hosur", sortOrder: 10 },

  { city: "Howrah", name: "Indian Institute of Engineering Science and Technology, Shibpur", sortOrder: 10 },
  { city: "Howrah", name: "Seacom Engineering College", sortOrder: 20 },
  { city: "Hubballi", name: "KLE Technological University", sortOrder: 10 },
  { city: "Hubballi", name: "Jain College of Engineering and Technology", sortOrder: 20 },
  { city: "Jabalpur", name: "Jabalpur Engineering College", sortOrder: 10 },
  { city: "Jabalpur", name: "Indian Institute of Information Technology, Design and Manufacturing Jabalpur", sortOrder: 20 },
  { city: "Jalgaon", name: "Government College of Engineering, Jalgaon", sortOrder: 10 },
  { city: "Jalgaon", name: "SSBT's College of Engineering and Technology", sortOrder: 20 },
  { city: "Jamnagar", name: "Government Engineering College, Jamnagar", sortOrder: 10 },
  { city: "Kakinada", name: "University College of Engineering, Kakinada (JNTUK)", sortOrder: 10 },
  { city: "Kalaburagi", name: "Poojya Doddappa Appa College of Engineering", sortOrder: 10 },
  { city: "Kalaburagi", name: "Khaja Bandanawaz College of Engineering", sortOrder: 20 },
  { city: "Kanchipuram", name: "Indian Institute of Information Technology, Design and Manufacturing Kancheepuram", sortOrder: 10 },
  { city: "Kanchipuram", name: "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya", sortOrder: 20 },
  { city: "Kanchipuram", name: "Thirumalai Engineering College", sortOrder: 30 },
  { city: "Karaikal", name: "Bharathiyar College of Engineering and Technology", sortOrder: 10 },
  { city: "Kasaragod", name: "LBS College of Engineering", sortOrder: 10 },
  { city: "Kasaragod", name: "College of Engineering, Trikaripur", sortOrder: 20 },
  { city: "Khammam", name: "Swarna Bharathi Institute of Science and Technology", sortOrder: 10 },
  { city: "Kochi", name: "Model Engineering College", sortOrder: 10 },
  { city: "Kolhapur", name: "Government College of Engineering, Kolhapur", sortOrder: 10 },
  { city: "Kolhapur", name: "D. Y. Patil College of Engineering and Technology", sortOrder: 20 },
  { city: "Kollam", name: "TKM College of Engineering", sortOrder: 10 },
  { city: "Kota", name: "University Engineering College, Kota (Rajasthan Technical University)", sortOrder: 10 },
  { city: "Kottayam", name: "Amal Jyothi College of Engineering", sortOrder: 10 },

  { city: "Kurnool", name: "G. Pulla Reddy Engineering College", sortOrder: 10 },
  { city: "Malda", name: "Ghani Khan Choudhury Institute of Engineering and Technology", sortOrder: 10 },
  { city: "Meerut", name: "Meerut Institute of Engineering and Technology", sortOrder: 10 },
  { city: "Moradabad", name: "Moradabad Institute of Technology", sortOrder: 10 },
  { city: "Moradabad", name: "IFTM University", sortOrder: 20 },
  { city: "Muzaffarpur", name: "Muzaffarpur Institute of Technology", sortOrder: 10 },
  { city: "Mysuru", name: "Sri Jayachamarajendra College of Engineering", sortOrder: 10 },
  { city: "Mysuru", name: "The National Institute of Engineering", sortOrder: 20 },
  { city: "Nanded", name: "Shri Guru Gobind Singhji Institute of Engineering and Technology", sortOrder: 10 },
  { city: "Navi Mumbai", name: "Fr. C. Rodrigues Institute of Technology", sortOrder: 10 },
  { city: "Navi Mumbai", name: "Terna Engineering College", sortOrder: 20 },
  { city: "Nellore", name: "Narayana Engineering College", sortOrder: 10 },
  { city: "Noida", name: "Jaypee Institute of Information Technology", sortOrder: 10 },
  { city: "Noida", name: "Amity School of Engineering and Technology, Noida", sortOrder: 20 },
  { city: "Rajahmundry", name: "Godavari Institute of Engineering and Technology", sortOrder: 10 },
  { city: "Salem", name: "Sona College of Technology", sortOrder: 10 },
  { city: "Salem", name: "Government College of Engineering, Salem", sortOrder: 20 },
  { city: "Siliguri", name: "Siliguri Institute of Technology", sortOrder: 10 },
  { city: "Solapur", name: "Walchand Institute of Technology", sortOrder: 10 },
  { city: "Sonipat", name: "Indian Institute of Information Technology, Sonepat", sortOrder: 10 },
  { city: "Sonipat", name: "Hindu College of Engineering", sortOrder: 20 },
  { city: "Thrissur", name: "Government Engineering College, Thrissur", sortOrder: 10 },
  { city: "Tirunelveli", name: "Government College of Engineering, Tirunelveli", sortOrder: 10 },
  { city: "Tirunelveli", name: "Francis Xavier Engineering College", sortOrder: 20 },
  { city: "Tumakuru", name: "Siddaganga Institute of Technology", sortOrder: 10 },
  { city: "Yamunanagar", name: "Seth Jai Parkash Mukand Lal Institute of Engineering and Technology", sortOrder: 10 },
];

export const DESIGN_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Ahmedabad", name: "National Institute of Design (NID), Ahmedabad", sortOrder: 1 },
  { city: "Ahmedabad", name: "Unitedworld Institute of Design (UID)", sortOrder: 20 },

  { city: "Delhi", name: "National Institute of Fashion Technology (NIFT), Delhi", sortOrder: 10 },
  { city: "Delhi", name: "Pearl Academy, Delhi", sortOrder: 20 },

  { city: "Mumbai", name: "National Institute of Fashion Technology (NIFT), Mumbai", sortOrder: 10 },
  { city: "Mumbai", name: "Sir J J Institute of Applied Art", sortOrder: 20 },
  { city: "Mumbai", name: "Pearl Academy, Mumbai", sortOrder: 30 },
  { city: "Mumbai", name: "Indian School of Design and Innovation (ISDI)", sortOrder: 40 },

  { city: "Bengaluru", name: "National Institute of Fashion Technology (NIFT), Bengaluru", sortOrder: 10 },
  { city: "Bengaluru", name: "National Institute of Design (NID), Bengaluru", sortOrder: 20 },
  { city: "Bengaluru", name: "Srishti Manipal Institute of Art, Design and Technology", sortOrder: 30 },
  { city: "Bengaluru", name: "Vogue Institute of Art and Design", sortOrder: 40 },

  { city: "Chennai", name: "National Institute of Fashion Technology (NIFT), Chennai", sortOrder: 10 },

  { city: "Kolkata", name: "National Institute of Fashion Technology (NIFT), Kolkata", sortOrder: 10 },

  { city: "Hyderabad", name: "National Institute of Fashion Technology (NIFT), Hyderabad", sortOrder: 10 },

  { city: "Pune", name: "Symbiosis Institute of Design", sortOrder: 10 },
  { city: "Pune", name: "MIT Institute of Design", sortOrder: 20 },

  { city: "Bhopal", name: "National Institute of Fashion Technology (NIFT), Bhopal", sortOrder: 10 },
  { city: "Bhubaneswar", name: "National Institute of Fashion Technology (NIFT), Bhubaneswar", sortOrder: 10 },
  { city: "Gandhinagar", name: "National Institute of Fashion Technology (NIFT), Gandhinagar", sortOrder: 10 },
  { city: "Gandhinagar", name: "National Institute of Design (NID), Gandhinagar Campus", sortOrder: 20 },
  { city: "Jodhpur", name: "National Institute of Fashion Technology (NIFT), Jodhpur", sortOrder: 10 },
  { city: "Kannur", name: "National Institute of Fashion Technology (NIFT), Kannur", sortOrder: 10 },
  { city: "Patna", name: "National Institute of Fashion Technology (NIFT), Patna", sortOrder: 10 },
  { city: "Shillong", name: "National Institute of Fashion Technology (NIFT), Shillong", sortOrder: 10 },
  { city: "Srinagar", name: "National Institute of Fashion Technology (NIFT), Srinagar", sortOrder: 10 },

  { city: "Vijayawada", name: "National Institute of Design (NID), Andhra Pradesh Campus", sortOrder: 10 },
  { city: "Kurukshetra", name: "National Institute of Design (NID), Kurukshetra Campus", sortOrder: 10 },
  { city: "Jorhat", name: "National Institute of Design (NID), Assam Campus", sortOrder: 10 },

  { city: "Jaipur", name: "International Institute of Craft and Design (IICD), Jaipur", sortOrder: 10 },
  { city: "Coimbatore", name: "DJ Academy of Design", sortOrder: 10 },

  { city: "Noida", name: "Pearl Academy, Noida", sortOrder: 10 },
];

export const MEDICAL_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Delhi", name: "All India Institute of Medical Sciences (AIIMS), Delhi", nirfRank: 1 },
  { city: "Delhi", name: "Maulana Azad Medical College", sortOrder: 10 },
  { city: "Delhi", name: "Lady Hardinge Medical College", sortOrder: 20 },
  { city: "Delhi", name: "University College of Medical Sciences (UCMS)", sortOrder: 30 },

  { city: "Chandigarh", name: "Postgraduate Institute of Medical Education and Research (PGIMER)", sortOrder: 5 },
  { city: "Chandigarh", name: "Government Medical College and Hospital (GMCH-32)", sortOrder: 15 },

  { city: "Vellore", name: "Christian Medical College (CMC), Vellore", sortOrder: 5 },

  { city: "Bengaluru", name: "National Institute of Mental Health and Neurosciences (NIMHANS)", sortOrder: 5 },
  { city: "Bengaluru", name: "St John's Medical College", sortOrder: 15 },
  { city: "Bengaluru", name: "Bangalore Medical College and Research Institute", sortOrder: 25 },

  { city: "Lucknow", name: "Sanjay Gandhi Postgraduate Institute of Medical Sciences (SGPGIMS)", sortOrder: 10 },
  { city: "Lucknow", name: "King George's Medical University (KGMU)", sortOrder: 20 },

  { city: "Pune", name: "Armed Forces Medical College (AFMC)", sortOrder: 10 },
  { city: "Pune", name: "B J Government Medical College", sortOrder: 20 },

  { city: "Puducherry", name: "Jawaharlal Institute of Postgraduate Medical Education and Research (JIPMER)", sortOrder: 10 },

  { city: "Manipal", name: "Kasturba Medical College (KMC), Manipal", sortOrder: 10 },

  { city: "Mumbai", name: "Seth GS Medical College and KEM Hospital", sortOrder: 10 },
  { city: "Mumbai", name: "Grant Medical College and Sir JJ Hospital", sortOrder: 20 },
  { city: "Mumbai", name: "Topiwala National Medical College (Nair Hospital)", sortOrder: 30 },

  { city: "Chennai", name: "Madras Medical College", sortOrder: 10 },
  { city: "Chennai", name: "Stanley Medical College", sortOrder: 20 },
  { city: "Chennai", name: "Sri Ramachandra Institute of Higher Education and Research", sortOrder: 30 },

  { city: "Varanasi", name: "Institute of Medical Sciences, Banaras Hindu University (IMS-BHU)", sortOrder: 10 },

  { city: "Hyderabad", name: "Nizam's Institute of Medical Sciences (NIMS)", sortOrder: 10 },
  { city: "Hyderabad", name: "Osmania Medical College", sortOrder: 20 },

  { city: "Kolkata", name: "Institute of Post Graduate Medical Education and Research (IPGMER) and SSKM Hospital", sortOrder: 10 },
  { city: "Kolkata", name: "Calcutta National Medical College", sortOrder: 20 },

  { city: "Jodhpur", name: "All India Institute of Medical Sciences (AIIMS), Jodhpur", sortOrder: 10 },
  { city: "Bhopal", name: "All India Institute of Medical Sciences (AIIMS), Bhopal", sortOrder: 10 },
  { city: "Bhubaneswar", name: "All India Institute of Medical Sciences (AIIMS), Bhubaneswar", sortOrder: 10 },
  { city: "Patna", name: "All India Institute of Medical Sciences (AIIMS), Patna", sortOrder: 10 },
  { city: "Raipur", name: "All India Institute of Medical Sciences (AIIMS), Raipur", sortOrder: 10 },
  { city: "Rishikesh", name: "All India Institute of Medical Sciences (AIIMS), Rishikesh", sortOrder: 10 },
  { city: "Nagpur", name: "All India Institute of Medical Sciences (AIIMS), Nagpur", sortOrder: 10 },
  { city: "Guwahati", name: "All India Institute of Medical Sciences (AIIMS), Guwahati", sortOrder: 10 },
  { city: "Rajkot", name: "All India Institute of Medical Sciences (AIIMS), Rajkot", sortOrder: 10 },
  { city: "Bathinda", name: "All India Institute of Medical Sciences (AIIMS), Bathinda", sortOrder: 10 },
  { city: "Gorakhpur", name: "All India Institute of Medical Sciences (AIIMS), Gorakhpur", sortOrder: 10 },
  { city: "Deoghar", name: "All India Institute of Medical Sciences (AIIMS), Deoghar", sortOrder: 10 },
  { city: "Raebareli", name: "All India Institute of Medical Sciences (AIIMS), Raebareli", sortOrder: 10 },
  { city: "Madurai", name: "All India Institute of Medical Sciences (AIIMS), Madurai", sortOrder: 10 },
  { city: "Bilaspur", name: "All India Institute of Medical Sciences (AIIMS), Bilaspur (Himachal Pradesh)", sortOrder: 10 },
  { city: "Guntur", name: "All India Institute of Medical Sciences (AIIMS), Mangalagiri", sortOrder: 10 },
  { city: "Kolkata", name: "All India Institute of Medical Sciences (AIIMS), Kalyani", sortOrder: 30 },
  { city: "Hyderabad", name: "All India Institute of Medical Sciences (AIIMS), Bibinagar", sortOrder: 30 },

  { city: "Nagpur", name: "Government Medical College (GMC), Nagpur", sortOrder: 20 },
  { city: "Nagpur", name: "Indira Gandhi Government Medical College (IGGMC), Nagpur", sortOrder: 30 },
  { city: "Indore", name: "Mahatma Gandhi Memorial Medical College (MGM), Indore", sortOrder: 10 },
  { city: "Jaipur", name: "Sawai Man Singh (SMS) Medical College", sortOrder: 10 },
  { city: "Coimbatore", name: "Coimbatore Medical College", sortOrder: 10 },
  { city: "Patna", name: "Patna Medical College and Hospital (PMCH)", sortOrder: 10 },
  { city: "Bhopal", name: "Gandhi Medical College, Bhopal", sortOrder: 20 },
  { city: "Kanpur", name: "GSVM Medical College, Kanpur", sortOrder: 10 },
  { city: "Vadodara", name: "Government Medical College (Sir Sayajirao General Hospital), Vadodara", sortOrder: 10 },
  { city: "Nashik", name: "Maharashtra University of Health Sciences (MUHS)", sortOrder: 10 },
  { city: "Nashik", name: "Dr Vasantrao Pawar Medical College, Nashik", sortOrder: 20 },
  { city: "Guwahati", name: "Guwahati Medical College and Hospital (GMCH)", sortOrder: 20 },
  { city: "Bhubaneswar", name: "IMS and SUM Hospital", sortOrder: 20 },
  { city: "Bhubaneswar", name: "Kalinga Institute of Medical Sciences (KIMS), Bhubaneswar", sortOrder: 30 },
  { city: "Thiruvananthapuram", name: "Government Medical College, Thiruvananthapuram", sortOrder: 10 },
  { city: "Thiruvananthapuram", name: "Sree Chitra Tirunal Institute for Medical Sciences and Technology (SCTIMST)", sortOrder: 20 },
  { city: "Visakhapatnam", name: "Andhra Medical College", sortOrder: 10 },
  { city: "Visakhapatnam", name: "GITAM Institute of Medical Sciences and Research", sortOrder: 20 },
  { city: "Amritsar", name: "Government Medical College, Amritsar", sortOrder: 10 },
  { city: "Ludhiana", name: "Christian Medical College (CMC), Ludhiana", sortOrder: 10 },
  { city: "Surat", name: "Surat Municipal Institute of Medical Education and Research (SMIMER)", sortOrder: 10 },
  { city: "Surat", name: "Government Medical College, Surat", sortOrder: 20 },

  { city: "Agra", name: "Sarojini Naidu Medical College (SNMC), Agra", sortOrder: 10 },
  { city: "Ajmer", name: "Jawaharlal Nehru Medical College, Ajmer", sortOrder: 10 },
  { city: "Alappuzha", name: "Government T.D. Medical College, Alappuzha", sortOrder: 10 },
  { city: "Aligarh", name: "Jawaharlal Nehru Medical College (AMU)", sortOrder: 10 },
  { city: "Alwar", name: "Government Medical College, Alwar", sortOrder: 10 },
  { city: "Ambala", name: "Maharishi Markandeshwar Institute of Medical Sciences and Research (MMIMSR), Mullana", sortOrder: 10 },
  { city: "Ambikapur", name: "Rajmata Shrimati Devendra Kumari Singhdeo Government Medical College, Ambikapur", sortOrder: 10 },
  { city: "Amravati", name: "Government Medical College, Amravati", sortOrder: 10 },
  { city: "Amravati", name: "Dr. Panjabrao Deshmukh Memorial Medical College (PDMMC), Amravati", sortOrder: 20 },
  { city: "Anantapur", name: "Government Medical College, Anantapur", sortOrder: 10 },
  { city: "Aurangabad", name: "Government Medical College, Aurangabad", sortOrder: 10 },
  { city: "Ayodhya", name: "Rajarshi Dashrath Autonomous State Medical College, Ayodhya", sortOrder: 10 },
  { city: "Balasore", name: "Fakir Mohan Medical College and Hospital, Balasore", sortOrder: 10 },
  { city: "Ballari", name: "Vijayanagar Institute of Medical Sciences (VIMS), Ballari", sortOrder: 10 },
  { city: "Bareilly", name: "Rohilkhand Medical College and Hospital, Bareilly", sortOrder: 10 },
  { city: "Belagavi", name: "Jawaharlal Nehru Medical College, Belagavi (KLE)", sortOrder: 10 },
  { city: "Berhampur", name: "Maharaja Krishna Chandra Gajapati (MKCG) Medical College and Hospital, Berhampur", sortOrder: 10 },
  { city: "Bhagalpur", name: "Jawaharlal Nehru Medical College, Bhagalpur", sortOrder: 10 },
  { city: "Bharatpur", name: "Government Medical College, Bharatpur", sortOrder: 10 },

  { city: "Bhavnagar", name: "Government Medical College, Bhavnagar", sortOrder: 10 },
  { city: "Bidar", name: "Bidar Institute of Medical Sciences, Bidar", sortOrder: 10 },
  { city: "Bikaner", name: "Sardar Patel Medical College, Bikaner", sortOrder: 10 },
  { city: "Bulandshahr", name: "Kalyan Singh Government Medical College, Bulandshahr", sortOrder: 10 },
  { city: "Burdwan", name: "Burdwan Medical College, Burdwan", sortOrder: 10 },
  { city: "Cuttack", name: "S.C.B. Medical College and Hospital, Cuttack", sortOrder: 10 },
  { city: "Darbhanga", name: "Darbhanga Medical College and Hospital, Darbhanga", sortOrder: 10 },
  { city: "Dibrugarh", name: "Assam Medical College, Dibrugarh", sortOrder: 10 },
  { city: "Erode", name: "Government Erode Medical College and Hospital, Erode", sortOrder: 10 },
  { city: "Faridabad", name: "Shri Atal Bihari Vajpayee Government Medical College, Faridabad", sortOrder: 10 },
  { city: "Faridabad", name: "ESIC Medical College and Hospital, Faridabad", sortOrder: 20 },
  { city: "Ghaziabad", name: "Santosh Medical College and Hospital, Ghaziabad", sortOrder: 10 },
  { city: "Gwalior", name: "Gajra Raja Medical College, Gwalior", sortOrder: 10 },
  { city: "Haldwani", name: "Government Medical College, Haldwani", sortOrder: 10 },
  { city: "Haridwar", name: "University of Patanjali, Haridwar", sortOrder: 10 },

  { city: "Howrah", name: "Sarat Chandra Chattopadhyay Government Medical College and Hospital", sortOrder: 10 },
  { city: "Jabalpur", name: "Netaji Subhash Chandra Bose Medical College", sortOrder: 10 },
  { city: "Jalgaon", name: "Government Medical College, Jalgaon", sortOrder: 10 },
  { city: "Jamnagar", name: "Shri M.P. Shah Medical College", sortOrder: 10 },
  { city: "Jamnagar", name: "Gujarat Ayurved University", sortOrder: 20 },
  { city: "Junagadh", name: "GMERS Medical College and Hospital, Junagadh", sortOrder: 10 },
  { city: "Kakinada", name: "Rangaraya Medical College", sortOrder: 10 },
  { city: "Kalaburagi", name: "Mahadevappa Rampure Medical College", sortOrder: 10 },
  { city: "Kanchipuram", name: "Meenakshi Medical College Hospital and Research Institute", sortOrder: 10 },
  { city: "Karimnagar", name: "Government Medical College, Karimnagar", sortOrder: 10 },
  { city: "Karimnagar", name: "Chalmeda Anand Rao Institute of Medical Sciences", sortOrder: 20 },
  { city: "Karimnagar", name: "Prathima Institute of Medical Sciences", sortOrder: 30 },
  { city: "Karnal", name: "Kalpana Chawla Government Medical College", sortOrder: 10 },
  { city: "Khammam", name: "Mamata Medical College", sortOrder: 10 },
  { city: "Kochi", name: "Government Medical College, Ernakulam", sortOrder: 10 },
  { city: "Kochi", name: "Amrita Institute of Medical Sciences", sortOrder: 20 },
  { city: "Kolhapur", name: "Rajarshi Chhatrapati Shahu Maharaj Government Medical College", sortOrder: 10 },
  { city: "Kollam", name: "Travancore Medical College", sortOrder: 10 },
  { city: "Kota", name: "Government Medical College, Kota", sortOrder: 10 },
  { city: "Kottayam", name: "Government Medical College, Kottayam", sortOrder: 10 },

  { city: "Kurnool", name: "Kurnool Medical College", sortOrder: 10 },
  { city: "Malda", name: "Malda Medical College and Hospital", sortOrder: 10 },
  { city: "Meerut", name: "Lala Lajpat Rai Memorial Medical College", sortOrder: 10 },
  { city: "Meerut", name: "Subharti Medical College", sortOrder: 20 },
  { city: "Moradabad", name: "Teerthanker Mahaveer Medical College and Research Centre", sortOrder: 10 },
  { city: "Muzaffarpur", name: "Sri Krishna Medical College and Hospital", sortOrder: 10 },
  { city: "Mysuru", name: "Mysore Medical College and Research Institute", sortOrder: 10 },
  { city: "Mysuru", name: "JSS Medical College", sortOrder: 20 },
  { city: "Nanded", name: "Dr. Shankarrao Chavan Government Medical College", sortOrder: 10 },
  { city: "Navi Mumbai", name: "Padmashree Dr. D.Y. Patil Medical College, Hospital and Research Centre", sortOrder: 10 },
  { city: "Navi Mumbai", name: "Terna Medical College", sortOrder: 20 },
  { city: "Nellore", name: "Narayana Medical College", sortOrder: 10 },
  { city: "Panaji", name: "Goa Medical College", sortOrder: 10 },
  { city: "Rajahmundry", name: "GSL Medical College and General Hospital", sortOrder: 10 },
  { city: "Salem", name: "Government Mohan Kumaramangalam Medical College", sortOrder: 10 },
  { city: "Siliguri", name: "North Bengal Medical College and Hospital", sortOrder: 10 },
  { city: "Solapur", name: "Dr. Vaishampayan Memorial Government Medical College", sortOrder: 10 },
  { city: "Sonipat", name: "Bhagat Phool Singh Government Medical College for Women", sortOrder: 10 },
  { city: "Thrissur", name: "Government Medical College, Thrissur", sortOrder: 10 },
  { city: "Tirunelveli", name: "Tirunelveli Medical College", sortOrder: 10 },
  { city: "Tumakuru", name: "Sri Siddhartha Medical College", sortOrder: 10 },
];

export const MANAGEMENT_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Ahmedabad", name: "Indian Institute of Management (IIM), Ahmedabad", sortOrder: 5 },
  { city: "Bengaluru", name: "Indian Institute of Management (IIM), Bangalore", sortOrder: 5 },
  { city: "Kolkata", name: "Indian Institute of Management (IIM), Calcutta", sortOrder: 5 },
  { city: "Lucknow", name: "Indian Institute of Management (IIM), Lucknow", sortOrder: 10 },
  { city: "Indore", name: "Indian Institute of Management (IIM), Indore", sortOrder: 10 },
  { city: "Kozhikode", name: "Indian Institute of Management (IIM), Kozhikode", sortOrder: 10 },

  { city: "Delhi", name: "Faculty of Management Studies (FMS), University of Delhi", sortOrder: 10 },
  { city: "Delhi", name: "Delhi School of Economics", sortOrder: 20 },

  { city: "Gurugram", name: "Management Development Institute (MDI), Gurugram", sortOrder: 10 },

  { city: "Mumbai", name: "Jamnalal Bajaj Institute of Management Studies (JBIMS)", sortOrder: 10 },
  { city: "Mumbai", name: "S P Jain Institute of Management and Research (SPJIMR)", sortOrder: 20 },
  { city: "Mumbai", name: "Narsee Monjee Institute of Management Studies (NMIMS)", sortOrder: 30 },

  { city: "Pune", name: "Symbiosis Institute of Business Management (SIBM), Pune", sortOrder: 10 },

  { city: "Jamshedpur", name: "Xavier School of Management (XLRI), Jamshedpur", sortOrder: 10 },

  { city: "Chennai", name: "Great Lakes Institute of Management", sortOrder: 10 },
  { city: "Chennai", name: "Loyola Institute of Business Administration (LIBA)", sortOrder: 20 },

  { city: "Shillong", name: "Indian Institute of Management (IIM), Shillong", sortOrder: 20 },
  { city: "Rohtak", name: "Indian Institute of Management (IIM), Rohtak", sortOrder: 20 },
  { city: "Ranchi", name: "Indian Institute of Management (IIM), Ranchi", sortOrder: 20 },
  { city: "Raipur", name: "Indian Institute of Management (IIM), Raipur", sortOrder: 20 },
  { city: "Tiruchirappalli", name: "Indian Institute of Management (IIM), Tiruchirappalli", sortOrder: 20 },
  { city: "Kashipur", name: "Indian Institute of Management (IIM), Kashipur", sortOrder: 20 },
  { city: "Udaipur", name: "Indian Institute of Management (IIM), Udaipur", sortOrder: 20 },
  { city: "Nagpur", name: "Indian Institute of Management (IIM), Nagpur", sortOrder: 20 },
  { city: "Visakhapatnam", name: "Indian Institute of Management (IIM), Visakhapatnam", sortOrder: 20 },
  { city: "Gaya", name: "Indian Institute of Management (IIM), Bodh Gaya", sortOrder: 20 },
  { city: "Shimla", name: "Indian Institute of Management (IIM), Sirmaur", sortOrder: 20 },
  { city: "Sambalpur", name: "Indian Institute of Management (IIM), Sambalpur", sortOrder: 20 },
  { city: "Amritsar", name: "Indian Institute of Management (IIM), Amritsar", sortOrder: 20 },
  { city: "Jammu", name: "Indian Institute of Management (IIM), Jammu", sortOrder: 20 },

  { city: "Bhubaneswar", name: "Xavier Institute of Management, Bhubaneswar (XIMB)", sortOrder: 30 },
  { city: "Chandigarh", name: "University Business School (UBS), Panjab University", sortOrder: 10 },
  { city: "Indore", name: "Prestige Institute of Management and Research, Indore", sortOrder: 10 },
  { city: "Lucknow", name: "Jaipuria Institute of Management, Lucknow", sortOrder: 10 },

  { city: "Bharuch", name: "Narmada College of Management, Bharuch", sortOrder: 10 },
  { city: "Ghaziabad", name: "Institute of Management Studies, Ghaziabad", sortOrder: 10 },
  { city: "Gwalior", name: "ITM University, School of Management, Gwalior", sortOrder: 10 },
  { city: "Kochi", name: "Rajagiri College of Social Sciences", sortOrder: 10 },
  { city: "Navi Mumbai", name: "D.Y. Patil University School of Management", sortOrder: 10 },
  { city: "Noida", name: "Jaipuria Institute of Management, Noida", sortOrder: 10 },
];

export const LAW_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Bengaluru", name: "National Law School of India University (NLSIU)", nirfRank: 1 },
  { city: "Delhi", name: "National Law University (NLU), Delhi", sortOrder: 10 },
  { city: "Delhi", name: "Faculty of Law, University of Delhi", sortOrder: 20 },
  { city: "Hyderabad", name: "NALSAR University of Law", sortOrder: 10 },
  { city: "Kolkata", name: "West Bengal National University of Juridical Sciences (NUJS)", sortOrder: 10 },
  { city: "Pune", name: "Symbiosis Law School, Pune", sortOrder: 10 },
  { city: "Pune", name: "ILS Law College", sortOrder: 20 },
  { city: "Gandhinagar", name: "Gujarat National Law University (GNLU)", sortOrder: 10 },
  { city: "Bhopal", name: "National Law Institute University (NLIU), Bhopal", sortOrder: 10 },
  { city: "Jodhpur", name: "National Law University, Jodhpur", sortOrder: 10 },
  { city: "Patiala", name: "Rajiv Gandhi National University of Law (RGNUL), Patiala", sortOrder: 10 },
  { city: "Lucknow", name: "Dr. Ram Manohar Lohiya National Law University", sortOrder: 10 },

  { city: "Patna", name: "Chanakya National Law University (CNLU), Patna", sortOrder: 10 },
  { city: "Guwahati", name: "National Law University and Judicial Academy, Assam", sortOrder: 10 },
  { city: "Thiruvananthapuram", name: "Government Law College, Thiruvananthapuram", sortOrder: 10 },

  { city: "Agra", name: "Faculty of Law, Agra College", sortOrder: 10 },
  { city: "Belagavi", name: "Raja Lakhamgouda Law College (Karnatak Law Society)", sortOrder: 10 },
  { city: "Bhavnagar", name: "Sheth H.J. Law College, Bhavnagar", sortOrder: 10 },
  { city: "Greater Noida", name: "Sharda University School of Law, Greater Noida", sortOrder: 10 },
  { city: "Gwalior", name: "Madhav Law College, Gwalior", sortOrder: 10 },
  { city: "Jabalpur", name: "Hitkarini Law College", sortOrder: 10 },
  { city: "Kochi", name: "Government Law College, Ernakulam", sortOrder: 10 },
  { city: "Kolhapur", name: "Shahaji Law College", sortOrder: 10 },
  { city: "Noida", name: "Amity Law School, Noida", sortOrder: 10 },
  { city: "Sonipat", name: "O.P. Jindal Global University (Jindal Global Law School)", sortOrder: 10 },
];

export const ARCHITECTURE_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Delhi", name: "School of Planning and Architecture (SPA), Delhi", sortOrder: 5 },
  { city: "Mumbai", name: "Sir J J College of Architecture", sortOrder: 10 },
  { city: "Mumbai", name: "Kamla Raheja Vidyanidhi Institute for Architecture (KRVIA)", sortOrder: 20 },
  { city: "Ahmedabad", name: "CEPT University", sortOrder: 10 },
  { city: "Chennai", name: "Anna University — School of Architecture and Planning", sortOrder: 10 },
  { city: "Bhopal", name: "School of Planning and Architecture (SPA), Bhopal", sortOrder: 10 },
  { city: "Vijayawada", name: "School of Planning and Architecture (SPA), Vijayawada", sortOrder: 10 },
  { city: "Pune", name: "Bharati Vidyapeeth College of Architecture", sortOrder: 10 },
];

export const COMMERCE_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Delhi", name: "Shri Ram College of Commerce (SRCC)", sortOrder: 5 },
  { city: "Delhi", name: "Lady Shri Ram College for Women", sortOrder: 15 },
  { city: "Delhi", name: "Hindu College", sortOrder: 25 },
  { city: "Delhi", name: "Hansraj College", sortOrder: 35 },
  { city: "Delhi", name: "Sri Venkateswara College", sortOrder: 45 },
  { city: "Delhi", name: "Gargi College", sortOrder: 55 },

  { city: "Mumbai", name: "Narsee Monjee College of Commerce and Economics", sortOrder: 10 },
  { city: "Mumbai", name: "H R College of Commerce and Economics", sortOrder: 20 },
  { city: "Mumbai", name: "Sydenham College of Commerce and Economics", sortOrder: 30 },

  { city: "Chennai", name: "Loyola College", sortOrder: 10 },
  { city: "Chennai", name: "Madras Christian College", sortOrder: 20 },

  { city: "Kolkata", name: "St. Xavier's College, Kolkata", sortOrder: 10 },
  { city: "Kolkata", name: "Presidency University", sortOrder: 20 },

  { city: "Bengaluru", name: "Christ University", sortOrder: 10 },
  { city: "Bengaluru", name: "Mount Carmel College", sortOrder: 20 },

  { city: "Pune", name: "Symbiosis College of Arts and Commerce", sortOrder: 10 },
  { city: "Nagpur", name: "Rashtrasant Tukadoji Maharaj Nagpur University (RTMNU)", sortOrder: 10 },
  { city: "Nagpur", name: "G S College of Commerce and Economics", sortOrder: 20 },

  { city: "Indore", name: "Shri Atal Bihari Vajpayee Government Arts and Commerce College", sortOrder: 10 },
  { city: "Guwahati", name: "Gauhati Commerce College", sortOrder: 10 },
  { city: "Chandigarh", name: "MCM DAV College for Women", sortOrder: 10 },
  { city: "Kanpur", name: "D A V College, Kanpur", sortOrder: 10 },
  { city: "Kanpur", name: "D B S College, Kanpur", sortOrder: 20 },
  { city: "Vadodara", name: "Faculty of Commerce, The Maharaja Sayajirao University of Baroda", sortOrder: 10 },
  { city: "Surat", name: "Navayug Arts and Commerce College", sortOrder: 10 },

  { city: "Belagavi", name: "KLS Gogte College of Commerce, Belagavi", sortOrder: 10 },
  { city: "Bharuch", name: "Narmada College of Science and Commerce, Bharuch", sortOrder: 10 },
  { city: "Bhuj", name: "Shree J.B. Thacker Commerce College, Bhuj", sortOrder: 10 },
  { city: "Jamnagar", name: "Shree Halar Commerce College", sortOrder: 10 },
  { city: "Kota", name: "Government Commerce College, Kota", sortOrder: 10 },
  { city: "Kurnool", name: "S.V.B. Government Degree College, Kurnool", sortOrder: 10 },
];

export const SCIENCE_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Bengaluru", name: "Indian Institute of Science (IISc), Bengaluru", sortOrder: 5 },
  { city: "Pune", name: "Indian Institute of Science Education and Research (IISER), Pune", sortOrder: 10 },
  { city: "Kolkata", name: "Indian Statistical Institute (ISI), Kolkata", sortOrder: 10 },
  { city: "Kolkata", name: "Presidency University", sortOrder: 20 },
  { city: "Delhi", name: "St. Stephen's College", sortOrder: 10 },
  { city: "Delhi", name: "Hindu College", sortOrder: 20 },
  { city: "Delhi", name: "Miranda House", sortOrder: 30 },
  { city: "Delhi", name: "Kirori Mal College", sortOrder: 40 },
  { city: "Mumbai", name: "St. Xavier's College, Mumbai", sortOrder: 10 },
  { city: "Chennai", name: "Loyola College", sortOrder: 10 },
  { city: "Thiruvananthapuram", name: "Indian Institute of Science Education and Research (IISER), Thiruvananthapuram", sortOrder: 10 },
  { city: "Mohali", name: "Indian Institute of Science Education and Research (IISER), Mohali", sortOrder: 10 },
  { city: "Bhopal", name: "Indian Institute of Science Education and Research (IISER), Bhopal", sortOrder: 10 },
  { city: "Chandigarh", name: "Panjab University", sortOrder: 10 },
  { city: "Guwahati", name: "Gauhati University", sortOrder: 10 },

  { city: "Bhuj", name: "Krantiguru Shyamji Krishna Verma Kachchh University, Bhuj", sortOrder: 10 },
  { city: "Bikaner", name: "Maharaja Ganga Singh University, Bikaner", sortOrder: 10 },
  { city: "Burdwan", name: "University of Burdwan, Burdwan", sortOrder: 10 },
  { city: "Darbhanga", name: "C.M. Science College, Darbhanga", sortOrder: 10 },
  { city: "Dibrugarh", name: "Dibrugarh University, Dibrugarh", sortOrder: 10 },
  { city: "Durg", name: "Government Science College, Durg", sortOrder: 10 },
  { city: "Haridwar", name: "Gurukula Kangri (Deemed to be University), Haridwar", sortOrder: 10 },
  { city: "Kalaburagi", name: "Central University of Karnataka", sortOrder: 10 },
  { city: "Kochi", name: "Cochin University of Science and Technology", sortOrder: 10 },
  { city: "Kohima", name: "Kohima Science College, Jotsoma", sortOrder: 10 },
  { city: "Panaji", name: "Goa University", sortOrder: 10 },
];

export const ARTS_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Delhi", name: "St. Stephen's College", sortOrder: 5 },
  { city: "Delhi", name: "Lady Shri Ram College for Women", sortOrder: 15 },
  { city: "Delhi", name: "Miranda House", sortOrder: 25 },
  { city: "Delhi", name: "Hindu College", sortOrder: 35 },
  { city: "Delhi", name: "Ramjas College", sortOrder: 45 },
  { city: "Delhi", name: "Daulat Ram College", sortOrder: 55 },
  { city: "Mumbai", name: "St. Xavier's College, Mumbai", sortOrder: 10 },
  { city: "Kolkata", name: "Presidency University", sortOrder: 10 },
  { city: "Kolkata", name: "Jadavpur University", sortOrder: 20 },
  { city: "Chennai", name: "Madras Christian College", sortOrder: 10 },
  { city: "Chennai", name: "Stella Maris College", sortOrder: 20 },
  { city: "Pune", name: "Fergusson College", sortOrder: 10 },
  { city: "Bengaluru", name: "Christ University", sortOrder: 10 },
  { city: "Bengaluru", name: "St. Joseph's College", sortOrder: 20 },
  { city: "Bhubaneswar", name: "Utkal University", sortOrder: 10 },
  { city: "Jaipur", name: "University of Rajasthan", sortOrder: 10 },
  { city: "Jaipur", name: "Maharaja's College, Jaipur", sortOrder: 20 },
  { city: "Jaipur", name: "Maharani College, Jaipur", sortOrder: 30 },
  { city: "Patna", name: "Patna University", sortOrder: 10 },
  { city: "Ranchi", name: "Ranchi University", sortOrder: 10 },

  { city: "Nagpur", name: "Kamla Nehru Mahavidyalaya", sortOrder: 10 },
  { city: "Coimbatore", name: "PSGR Krishnammal College for Women", sortOrder: 10 },
  { city: "Coimbatore", name: "PSG College of Arts and Science", sortOrder: 20 },
  { city: "Coimbatore", name: "Kongunadu Arts and Science College", sortOrder: 30 },
  { city: "Chandigarh", name: "DAV College, Chandigarh", sortOrder: 10 },
  { city: "Chandigarh", name: "Government College of Art, Chandigarh", sortOrder: 20 },
  { city: "Bhopal", name: "Hamidia College, Bhopal", sortOrder: 10 },
  { city: "Vadodara", name: "Faculty of Arts, The Maharaja Sayajirao University of Baroda", sortOrder: 10 },
  { city: "Nashik", name: "K.T.H.M. College, Nashik", sortOrder: 10 },
  { city: "Guwahati", name: "B. Borooah College", sortOrder: 10 },
  { city: "Guwahati", name: "Cotton University", sortOrder: 20 },
  { city: "Thiruvananthapuram", name: "University College, Thiruvananthapuram", sortOrder: 10 },
  { city: "Amritsar", name: "Khalsa College, Amritsar", sortOrder: 10 },
  { city: "Ludhiana", name: "Khalsa College for Women, Ludhiana", sortOrder: 10 },
  { city: "Surat", name: "M T B Arts College, Surat", sortOrder: 10 },

  { city: "Agra", name: "Agra College", sortOrder: 10 },
  { city: "Agra", name: "St. John's College, Agra", sortOrder: 20 },
  { city: "Ajmer", name: "Government College, Ajmer", sortOrder: 10 },
  { city: "Ajmer", name: "Sophia Girls' College (Autonomous), Ajmer", sortOrder: 20 },
  { city: "Alappuzha", name: "Sanatana Dharma College, Alappuzha", sortOrder: 10 },
  { city: "Alipurduar", name: "Alipurduar College", sortOrder: 10 },
  { city: "Alwar", name: "Babu Shobha Ram Government Arts College, Alwar", sortOrder: 10 },
  { city: "Ambala", name: "DAV College, Ambala City", sortOrder: 10 },
  { city: "Amravati", name: "Government Vidarbha Institute of Science and Humanities, Amravati", sortOrder: 10 },
  { city: "Anantapur", name: "Government College (Autonomous), Anantapur", sortOrder: 10 },
  { city: "Angul", name: "Government College (Autonomous), Angul", sortOrder: 10 },
  { city: "Ara", name: "Maharaja College, Ara", sortOrder: 10 },
  { city: "Ara", name: "H.P. Jain College, Ara", sortOrder: 20 },
  { city: "Asansol", name: "Banwarilal Bhalotia (B.B.) College, Asansol", sortOrder: 10 },
  { city: "Asansol", name: "Bidhan Chandra College, Asansol", sortOrder: 20 },
  { city: "Aurangabad", name: "Deogiri College, Aurangabad", sortOrder: 10 },
  { city: "Ayodhya", name: "K.S. Saket P.G. College, Ayodhya", sortOrder: 10 },
  { city: "Balasore", name: "Fakir Mohan Autonomous College, Balasore", sortOrder: 10 },
  { city: "Ballari", name: "Veerashaiva College, Ballari", sortOrder: 10 },
  { city: "Bareilly", name: "Bareilly College", sortOrder: 10 },
  { city: "Belagavi", name: "Sangolli Rayanna First Grade Constituent College, Belagavi", sortOrder: 10 },
  { city: "Berhampur", name: "Khallikote University, Berhampur", sortOrder: 10 },
  { city: "Bhagalpur", name: "T.N.B. College, Bhagalpur", sortOrder: 10 },
  { city: "Bhagalpur", name: "Marwari College, Bhagalpur", sortOrder: 20 },
  { city: "Bharatpur", name: "M.A.J. Government College, Bharatpur", sortOrder: 10 },
  { city: "Bharatpur", name: "Maharaja Surajmal Mahavidyalaya, Bharatpur", sortOrder: 20 },

  { city: "Bharuch", name: "Shri Jayendrapuri Arts and Science College, Bharuch", sortOrder: 10 },
  { city: "Bhavnagar", name: "Samaldas Arts College, Bhavnagar", sortOrder: 10 },
  { city: "Bhiwadi", name: "Baba Mohan Ram Kissan Government College, Bhiwadi", sortOrder: 10 },
  { city: "Bidar", name: "Government First Grade College, Bidar", sortOrder: 10 },
  { city: "Bokaro", name: "Bokaro Steel City College, Bokaro", sortOrder: 10 },
  { city: "Bulandshahr", name: "I.P. (P.G.) College, Bulandshahr", sortOrder: 10 },
  { city: "Burdwan", name: "Burdwan Raj College, Burdwan", sortOrder: 10 },
  { city: "Cuttack", name: "Ravenshaw University, Cuttack", sortOrder: 10 },
  { city: "Darbhanga", name: "C.M. College, Darbhanga", sortOrder: 10 },
  { city: "Durg", name: "Government Arts, Science and Commerce College, Durg", sortOrder: 10 },
  { city: "Faridabad", name: "Pt. Jawahar Lal Nehru Government College, Faridabad", sortOrder: 10 },
  { city: "Ghaziabad", name: "M.M.H. College, Ghaziabad", sortOrder: 10 },
  { city: "Greater Noida", name: "Gautam Buddha University, Greater Noida", sortOrder: 10 },
  { city: "Gwalior", name: "Jiwaji University, Gwalior", sortOrder: 10 },
  { city: "Haldwani", name: "Moti Ram Babu Ram Government Post Graduate College, Haldwani", sortOrder: 10 },
  { city: "Haridwar", name: "Dev Sanskriti Vishwavidyalaya, Haridwar", sortOrder: 10 },
  { city: "Hosur", name: "Government Arts and Science College, Hosur", sortOrder: 10 },

  { city: "Howrah", name: "Uluberia College", sortOrder: 10 },
  { city: "Jalgaon", name: "Moolji Jaitha College", sortOrder: 10 },
  { city: "Jamnagar", name: "D.K.V. Arts and Science College", sortOrder: 10 },
  { city: "Junagadh", name: "Bahauddin Arts College", sortOrder: 10 },
  { city: "Kakinada", name: "Pithapur Rajah's Government College", sortOrder: 10 },
  { city: "Kalaburagi", name: "Government College (Autonomous), Kalaburagi", sortOrder: 10 },
  { city: "Karaikal", name: "Arignar Anna Government Arts and Science College, Karaikal", sortOrder: 10 },
  { city: "Karimnagar", name: "SRR Government Arts and Science College", sortOrder: 10 },
  { city: "Karnal", name: "Dyal Singh College", sortOrder: 10 },
  { city: "Kasaragod", name: "Government College, Kasaragod", sortOrder: 10 },
  { city: "Katni", name: "Government Tilak Post Graduate College, Katni", sortOrder: 10 },
  { city: "Khammam", name: "SR and BGNR Government Arts and Science College", sortOrder: 10 },
  { city: "Kohima", name: "Kohima College", sortOrder: 10 },
  { city: "Kolhapur", name: "Rajaram College", sortOrder: 10 },
  { city: "Kollam", name: "TKM College of Arts and Science", sortOrder: 10 },
  { city: "Kollam", name: "Sree Narayana College", sortOrder: 20 },
  { city: "Kota", name: "Government Arts College, Kota", sortOrder: 10 },
  { city: "Kottayam", name: "CMS College, Kottayam", sortOrder: 10 },
  { city: "Kottayam", name: "Baselius College", sortOrder: 20 },

  { city: "Kurnool", name: "Government Degree College for Men, Kurnool", sortOrder: 10 },
  { city: "Malda", name: "Malda College", sortOrder: 10 },
  { city: "Meerut", name: "Meerut College", sortOrder: 10 },
  { city: "Meerut", name: "D.N. (P.G.) College, Meerut", sortOrder: 20 },
  { city: "Moradabad", name: "Hindu College, Moradabad", sortOrder: 10 },
  { city: "Muzaffarpur", name: "Langat Singh College", sortOrder: 10 },
  { city: "Mysuru", name: "Maharaja's College, University of Mysore", sortOrder: 10 },
  { city: "Nanded", name: "Yeshwant Mahavidyalaya, Nanded", sortOrder: 10 },
  { city: "Navi Mumbai", name: "Karmaveer Bhaurao Patil College, Vashi", sortOrder: 10 },
  { city: "Nellore", name: "V.R. College, Nellore", sortOrder: 10 },
  { city: "Panaji", name: "Dhempe College of Arts and Science, Panaji", sortOrder: 10 },
  { city: "Rajahmundry", name: "Government College (Autonomous), Rajahmundry", sortOrder: 10 },
  { city: "Salem", name: "Government Arts College, Salem", sortOrder: 10 },
  { city: "Siliguri", name: "Siliguri College", sortOrder: 10 },
  { city: "Solapur", name: "Walchand College of Arts and Science", sortOrder: 10 },
  { city: "Sonipat", name: "Tika Ram P.G. Girls College", sortOrder: 10 },
  { city: "Thrissur", name: "St. Thomas College, Thrissur", sortOrder: 10 },
  { city: "Thrissur", name: "Sree Kerala Varma College", sortOrder: 20 },
  { city: "Tirunelveli", name: "Sarah Tucker College", sortOrder: 10 },
  { city: "Tumakuru", name: "Sree Siddaganga College of Arts, Science and Commerce", sortOrder: 10 },
  { city: "Udupi", name: "Mahatma Gandhi Memorial College, Udupi", sortOrder: 10 },
  { city: "Yamunanagar", name: "D.A.V. College, Yamunanagar", sortOrder: 10 },
];

export const ANIMATION_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Mumbai", name: "Whistling Woods International", sortOrder: 10 },
  { city: "Mumbai", name: "Zee Institute of Creative Art (ZICA), Mumbai", sortOrder: 20 },
  { city: "Pune", name: "Maya Academy of Advanced Cinematics (MAAC), Pune", sortOrder: 10 },
  { city: "Bengaluru", name: "Srishti Manipal Institute of Art, Design and Technology", sortOrder: 10 },
  { city: "Delhi", name: "Zee Institute of Creative Art (ZICA), Delhi", sortOrder: 10 },
  { city: "Hyderabad", name: "Zee Institute of Creative Art (ZICA), Hyderabad", sortOrder: 10 },
  { city: "Kolkata", name: "Zee Institute of Creative Art (ZICA), Kolkata", sortOrder: 10 },
];

export const HOTEL_MANAGEMENT_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Delhi", name: "Institute of Hotel Management, Catering Technology and Applied Nutrition (IHM Pusa)", sortOrder: 5 },
  { city: "Delhi", name: "Oberoi Centre of Learning and Development", sortOrder: 15 },
  { city: "Mumbai", name: "Institute of Hotel Management (IHM), Mumbai", sortOrder: 10 },
  { city: "Chennai", name: "Institute of Hotel Management (IHM), Chennai", sortOrder: 10 },
  { city: "Kolkata", name: "Institute of Hotel Management (IHM), Kolkata", sortOrder: 10 },
  { city: "Pune", name: "Institute of Hotel Management (IHM), Pune", sortOrder: 10 },
  { city: "Ahmedabad", name: "Institute of Hotel Management (IHM), Ahmedabad", sortOrder: 10 },
  { city: "Hyderabad", name: "Institute of Hotel Management (IHM), Hyderabad", sortOrder: 10 },
  { city: "Manipal", name: "Welcomgroup Graduate School of Hotel Administration, Manipal", sortOrder: 10 },
];

export const AGRICULTURE_COLLEGE_SEEDS: SeedCollege[] = [
  { city: "Delhi", name: "Indian Agricultural Research Institute (IARI), Pusa", nirfRank: 1 },
  { city: "Ludhiana", name: "Punjab Agricultural University (PAU)", sortOrder: 10 },
  { city: "Bengaluru", name: "University of Agricultural Sciences (UAS), Bengaluru", sortOrder: 10 },
  { city: "Coimbatore", name: "Tamil Nadu Agricultural University (TNAU)", sortOrder: 10 },
  { city: "Anand", name: "Anand Agricultural University", sortOrder: 10 },
  { city: "Varanasi", name: "Institute of Agricultural Sciences, Banaras Hindu University", sortOrder: 10 },
  { city: "Kanpur", name: "Chandra Shekhar Azad University of Agriculture and Technology", sortOrder: 10 },
  { city: "Hisar", name: "Chaudhary Charan Singh Haryana Agricultural University", sortOrder: 10 },
  { city: "Akola", name: "Dr. Panjabrao Deshmukh Krishi Vidyapeeth", sortOrder: 10 },

  { city: "Ayodhya", name: "Acharya Narendra Deva University of Agriculture and Technology (NDUAT), Kumarganj", sortOrder: 10 },
  { city: "Bikaner", name: "Swami Keshwanand Rajasthan Agricultural University, Bikaner", sortOrder: 10 },
  { city: "Junagadh", name: "Junagadh Agricultural University", sortOrder: 10 },
  { city: "Karaikal", name: "Pandit Jawaharlal Nehru College of Agriculture and Research Institute", sortOrder: 10 },
  { city: "Karnal", name: "National Dairy Research Institute, Karnal", sortOrder: 10 },
  { city: "Kasaragod", name: "College of Agriculture, Padannakkad", sortOrder: 10 },
  { city: "Thrissur", name: "Kerala Agricultural University", sortOrder: 10 },
];

export const COLLEGE_SEEDS_BY_CATEGORY: Record<string, SeedCollege[]> = {
  Engineering: ENGINEERING_COLLEGE_SEEDS,
  Design: DESIGN_COLLEGE_SEEDS,
  Medical: MEDICAL_COLLEGE_SEEDS,
  Management: MANAGEMENT_COLLEGE_SEEDS,
  Law: LAW_COLLEGE_SEEDS,
  Architecture: ARCHITECTURE_COLLEGE_SEEDS,
  Commerce: COMMERCE_COLLEGE_SEEDS,
  Science: SCIENCE_COLLEGE_SEEDS,
  Arts: ARTS_COLLEGE_SEEDS,
  Animation: ANIMATION_COLLEGE_SEEDS,
  "Hotel Management": HOTEL_MANAGEMENT_COLLEGE_SEEDS,
  Agriculture: AGRICULTURE_COLLEGE_SEEDS,
};
