import type { ChecklistCategory, ChecklistPriority } from "@/types";

export interface ChecklistTemplateItem {
  category: ChecklistCategory;
  item: string;
  priority: ChecklistPriority;
}

/**
 * Starter checklist seeded into every new student's account right after onboarding,
 * so they land on a pre-populated packing list instead of an empty one.
 */
export const DEFAULT_CHECKLIST_TEMPLATE: ChecklistTemplateItem[] = [
  { category: "Documents", item: "Aadhaar Card", priority: "medium" },
  { category: "Documents", item: "Passport Photos", priority: "medium" },
  { category: "Documents", item: "Admission Letter", priority: "medium" },
  { category: "Documents", item: "Fee Receipt", priority: "medium" },
  { category: "Documents", item: "Bank Card", priority: "medium" },
  { category: "Clothes", item: "T-Shirts", priority: "medium" },
  { category: "Clothes", item: "Jeans", priority: "medium" },
  { category: "Clothes", item: "Kurtis", priority: "medium" },
  { category: "Clothes", item: "Leggings", priority: "medium" },
  { category: "Clothes", item: "Night Suit", priority: "medium" },
  { category: "Clothes", item: "Innerwear", priority: "medium" },
  { category: "Clothes", item: "Socks", priority: "medium" },
  { category: "Clothes", item: "Sweater", priority: "medium" },
  { category: "Clothes", item: "Jacket", priority: "medium" },
  { category: "Footwear", item: "Sports Shoes", priority: "medium" },
  { category: "Footwear", item: "Slippers", priority: "medium" },
  { category: "Footwear", item: "Bathroom Slippers", priority: "medium" },
  { category: "Footwear", item: "Sandals", priority: "medium" },
  { category: "Toiletries", item: "Toothbrush", priority: "medium" },
  { category: "Toiletries", item: "Toothpaste", priority: "medium" },
  { category: "Toiletries", item: "Soap", priority: "medium" },
  { category: "Toiletries", item: "Shampoo", priority: "medium" },
  { category: "Toiletries", item: "Conditioner", priority: "medium" },
  { category: "Toiletries", item: "Hair Oil", priority: "medium" },
  { category: "Toiletries", item: "Face Wash", priority: "medium" },
  { category: "Toiletries", item: "Moisturizer", priority: "medium" },
  { category: "Toiletries", item: "Sunscreen", priority: "medium" },
  { category: "Toiletries", item: "Deodorant", priority: "medium" },
  { category: "Hostel Essentials", item: "Bucket", priority: "medium" },
  { category: "Hostel Essentials", item: "Mug", priority: "medium" },
  { category: "Hostel Essentials", item: "Towel", priority: "medium" },
  { category: "Hostel Essentials", item: "Soap Case", priority: "medium" },
  { category: "Laundry", item: "Laundry Bag", priority: "medium" },
  { category: "Laundry", item: "Detergent", priority: "medium" },
  { category: "Laundry", item: "Hangers", priority: "medium" },
  { category: "Laundry", item: "Cloth Clips", priority: "medium" },
  { category: "Electronics", item: "Laptop", priority: "medium" },
  { category: "Electronics", item: "Laptop Charger", priority: "medium" },
  { category: "Electronics", item: "Phone Charger", priority: "medium" },
  { category: "Electronics", item: "Power Bank", priority: "medium" },
  { category: "Electronics", item: "Extension Board", priority: "medium" },
  { category: "Electronics", item: "Earphones", priority: "medium" },
  { category: "Electronics", item: "USB Drive", priority: "medium" },
  { category: "Electronics", item: "Mouse", priority: "medium" },
  { category: "Stationery", item: "Notebook", priority: "medium" },
  { category: "Stationery", item: "Pens", priority: "medium" },
  { category: "Stationery", item: "Pencils", priority: "medium" },
  { category: "Stationery", item: "Highlighter", priority: "medium" },
  { category: "Stationery", item: "Files", priority: "medium" },
  { category: "Stationery", item: "Scissors", priority: "medium" },
  { category: "Stationery", item: "Glue", priority: "medium" },
  { category: "Stationery", item: "Calculator", priority: "medium" },
  { category: "Kitchen", item: "Water Bottle", priority: "medium" },
  { category: "Kitchen", item: "Lunch Box", priority: "medium" },
  { category: "Kitchen", item: "Plate", priority: "medium" },
  { category: "Kitchen", item: "Bowl", priority: "medium" },
  { category: "Kitchen", item: "Spoon", priority: "medium" },
  { category: "Kitchen", item: "Coffee Mug", priority: "medium" },
  { category: "Kitchen", item: "Containers", priority: "medium" },
  { category: "Medicines", item: "First Aid Kit", priority: "medium" },
  { category: "Medicines", item: "Bandages", priority: "medium" },
  { category: "Medicines", item: "Thermometer", priority: "medium" },
  { category: "Medicines", item: "Pain Relief", priority: "medium" },
  { category: "Medicines", item: "ORS", priority: "medium" },
  { category: "Medicines", item: "Prescription Medicines", priority: "medium" },
  { category: "Emergency", item: "Padlock", priority: "medium" },
  { category: "Emergency", item: "Spare Keys", priority: "medium" },
  { category: "Emergency", item: "Torch", priority: "medium" },
  { category: "Emergency", item: "Personal Alarm", priority: "medium" },
  { category: "Hostel Essentials", item: "Bedsheet", priority: "medium" },
  { category: "Hostel Essentials", item: "Blanket", priority: "medium" },
  { category: "Hostel Essentials", item: "Pillow", priority: "medium" },
  { category: "Hostel Essentials", item: "Pillow Cover", priority: "medium" },
  { category: "Hostel Essentials", item: "Mattress Protector", priority: "medium" },
  { category: "Fashion Design Tools", item: "Sketchbook", priority: "medium" },
  { category: "Fashion Design Tools", item: "Color Pencils", priority: "medium" },
  { category: "Fashion Design Tools", item: "Markers", priority: "medium" },
  { category: "Fashion Design Tools", item: "Measuring Tape", priority: "medium" },
  { category: "Fashion Design Tools", item: "Fabric Scissors", priority: "medium" },
  { category: "Fashion Design Tools", item: "Tracing Paper", priority: "medium" },
  { category: "Fashion Design Tools", item: "Portfolio Folder", priority: "medium" },
  { category: "Miscellaneous", item: "Umbrella", priority: "medium" },
  { category: "Miscellaneous", item: "Backpack", priority: "medium" },
  { category: "Miscellaneous", item: "Travel Bag", priority: "medium" },
  { category: "Miscellaneous", item: "Mirror", priority: "medium" },
  { category: "Miscellaneous", item: "Sewing Kit", priority: "medium" },
  { category: "Miscellaneous", item: "Zip-lock Bags", priority: "medium" },
  { category: "Miscellaneous", item: "Notebook Lock", priority: "medium" },
  { category: "Miscellaneous", item: "Journal", priority: "medium" },
];
