import type { CanvasElement, ElementLayout } from "@/features/welcome/canvas-types";
import { sectionIndex } from "@/features/welcome/home-sections";

function L(x: number, y: number, scale = 1, rotation = 0): ElementLayout {
  return { x, y, scale, rotation, visible: true, zIndex: 0 };
}

function el(partial: Omit<CanvasElement, "section"> & { section: string }): CanvasElement {
  return { ...partial, section: sectionIndex(partial.section) };
}

const STICKER = (slug: string) => `/stickers/${slug}.webp`;

/** The full default arrangement of every draggable unit on the home screen, approximating
 * today's live layout. Nothing changes for visitors until an admin edits and saves a layout
 * via the "Home Screen" admin editor — this seed is the fallback. */
export const DEFAULT_HOME_ELEMENTS: CanvasElement[] = [
  // ---------- 0. HERO ----------
  el({
    id: "hero-card",
    section: "hero",
    kind: "card",
    shape: "plain",
    background: "white",
    textStyle: "heading",
    isHero: true,
    lines: ["a survival guide for", "Hostel Survival Guide", "Everything you need before move-in day 💌"],
    ctaLabel: "Open My Survival Board →",
    href: "#mental-prep",
    layouts: { mobile: L(50, 50, 1, -3), desktop: L(50, 50, 1, -3) },
  }),
  el({
    id: "hero-sticker-camera",
    section: "hero",
    kind: "image",
    src: STICKER("camera"),
    alt: "camera sticker",
    layouts: { mobile: L(14, 16, 1, -8), desktop: L(10, 18, 1.3, -8) },
  }),
  el({
    id: "hero-sticker-bow",
    section: "hero",
    kind: "image",
    src: STICKER("bow"),
    alt: "bow sticker",
    layouts: { mobile: L(86, 14, 1, 10), desktop: L(90, 16, 1.3, 10) },
  }),
  el({
    id: "hero-sticker-evil-eye",
    section: "hero",
    kind: "image",
    src: STICKER("evil-eye"),
    alt: "evil eye sticker",
    layouts: { mobile: L(88, 84, 1, -5), desktop: L(92, 82, 1.3, -5) },
  }),
  el({
    id: "hero-sticker-cherries",
    section: "hero",
    kind: "image",
    src: STICKER("cherries"),
    alt: "cherries sticker",
    layouts: { mobile: L(12, 86, 1, 6), desktop: L(8, 84, 1.3, 6) },
  }),
  el({
    id: "hero-sticker-headphones",
    section: "hero",
    kind: "image",
    src: STICKER("headphones"),
    alt: "headphones sticker",
    layouts: { mobile: L(16, 50, 0.9, -12), desktop: L(6, 50, 1.2, -12) },
  }),

  // ---------- 1. MENTAL PREP ----------
  el({
    id: "mp-heading",
    section: "mental-prep",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Mental Prep 💭"],
    layouts: { mobile: L(50, 6, 1, 0), desktop: L(50, 8, 1, 0) },
  }),
  el({
    id: "mp-sticker-1",
    section: "mental-prep",
    kind: "image",
    src: STICKER("okay-not-okay"),
    alt: "it's okay to not be okay sticker",
    layouts: { mobile: L(14, 18, 1, -6), desktop: L(8, 20, 1.2, -6) },
  }),
  el({
    id: "mp-sticker-2",
    section: "mental-prep",
    kind: "image",
    src: STICKER("trust-the-process"),
    alt: "trust the process sticker",
    layouts: { mobile: L(86, 18, 1, 8), desktop: L(92, 20, 1.2, 8) },
  }),
  el({
    id: "mp-sticker-3",
    section: "mental-prep",
    kind: "image",
    src: STICKER("good-things-coming"),
    alt: "good things are coming sticker",
    layouts: { mobile: L(14, 88, 1, -4), desktop: L(8, 85, 1.2, -4) },
  }),
  el({
    id: "mp-sticker-4",
    section: "mental-prep",
    kind: "image",
    src: STICKER("note-to-self"),
    alt: "note to self, you're doing your best sticker",
    layouts: { mobile: L(86, 88, 1, 5), desktop: L(92, 85, 1.2, 5) },
  }),
  el({
    id: "mp-note-1",
    section: "mental-prep",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    lines: ["First week = chaos.", "That's completely normal, promise."],
    layouts: { mobile: L(50, 28, 1, -6), desktop: L(22, 45, 1, -6) },
  }),
  el({
    id: "mp-note-2",
    section: "mental-prep",
    kind: "card",
    shape: "sticky",
    background: "pink",
    lines: ["Homesickness hits randomly", "usually day 4-5. it passes, fr."],
    layouts: { mobile: L(50, 48, 1, 4), desktop: L(50, 38, 1, 4) },
  }),
  el({
    id: "mp-note-3",
    section: "mental-prep",
    kind: "card",
    shape: "sticky",
    background: "blue",
    lines: ["Don't isolate yourself", "keep the door open (literally) 🚪"],
    layouts: { mobile: L(50, 68, 1, -3), desktop: L(78, 45, 1, -3) },
  }),
  el({
    id: "mp-image",
    section: "mental-prep",
    kind: "image",
    src: STICKER("bandaid-everything-okay"),
    alt: "Everything will be okay sticker",
    layouts: { mobile: L(50, 90, 1, -1.5), desktop: L(50, 85, 1, -1.5) },
  }),

  // ---------- 2. ROOM SETUP ----------
  el({
    id: "room-heading",
    section: "room-setup",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Room Setup 🛏️"],
    layouts: { mobile: L(50, 8, 1, 0), desktop: L(50, 10, 1, 0) },
  }),
  el({
    id: "room-polaroid-1",
    section: "room-setup",
    kind: "card",
    shape: "polaroid",
    emoji: "🔌",
    lines: ["bed near plug ✔"],
    layouts: { mobile: L(25, 32, 1, -5), desktop: L(22, 45, 1, -5) },
  }),
  el({
    id: "room-polaroid-2",
    section: "room-setup",
    kind: "card",
    shape: "polaroid",
    src: STICKER("extension-board"),
    lines: ["extension board ✔"],
    layouts: { mobile: L(75, 42, 1, 3), desktop: L(50, 40, 1, 3) },
  }),
  el({
    id: "room-polaroid-3",
    section: "room-setup",
    kind: "card",
    shape: "polaroid",
    emoji: "🗂️",
    lines: ["bedside organizer ✔"],
    layouts: { mobile: L(25, 62, 1, -2), desktop: L(78, 45, 1, -2) },
  }),
  el({
    id: "room-caption",
    section: "room-setup",
    kind: "card",
    shape: "quote",
    background: "none",
    lines: ["trust me on the plug point one"],
    highlight: { line: 0, substring: "plug point", color: "#cfeaff" },
    decoration: "arrow",
    layouts: { mobile: L(50, 85, 1, 0), desktop: L(50, 85, 1, 0) },
  }),

  // ---------- 3. SURVIVAL HACKS ----------
  el({
    id: "hacks-heading",
    section: "survival-hacks",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Survival Hacks ⚡"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "hacks-note-1",
    section: "survival-hacks",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    emoji: "⚡",
    lines: ["charging war is real"],
    layouts: { mobile: L(25, 28, 1, 7), desktop: L(22, 45, 1, 7) },
  }),
  el({
    id: "hacks-note-2",
    section: "survival-hacks",
    kind: "card",
    shape: "sticky",
    background: "blue",
    emoji: "🔌",
    lines: ["label your chargers"],
    layouts: { mobile: L(75, 28, 1, -8), desktop: L(50, 40, 1, -8) },
  }),
  el({
    id: "hacks-note-3",
    section: "survival-hacks",
    kind: "card",
    shape: "sticky",
    background: "pink",
    emoji: "🔋",
    lines: ["power bank is life"],
    layouts: { mobile: L(50, 48, 1, 4), desktop: L(78, 45, 1, 4) },
  }),
  el({
    id: "hacks-sticker-1",
    section: "survival-hacks",
    kind: "image",
    src: STICKER("charging-myself"),
    alt: "charging myself sticker",
    layouts: { mobile: L(12, 68, 1, 0), desktop: L(10, 75, 1.2, 0) },
  }),
  el({
    id: "hacks-sticker-2",
    section: "survival-hacks",
    kind: "image",
    src: STICKER("extension-board"),
    alt: "extension board sticker",
    layouts: { mobile: L(50, 68, 1, 0), desktop: L(50, 78, 1.2, 0) },
  }),
  el({
    id: "hacks-sticker-3",
    section: "survival-hacks",
    kind: "image",
    src: STICKER("headphones"),
    alt: "headphones sticker",
    layouts: { mobile: L(88, 68, 1, 0), desktop: L(90, 75, 1.2, 0) },
  }),
  el({
    id: "hacks-highlight",
    section: "survival-hacks",
    kind: "card",
    shape: "quote",
    background: "none",
    lines: ["don't leave gadgets unattended — ever."],
    highlight: { line: 0, substring: "don't leave gadgets unattended", color: "#baffc9" },
    layouts: { mobile: L(50, 90, 1, 0), desktop: L(50, 90, 1, 0) },
  }),

  // ---------- 4. BATHROOM REALITY ----------
  el({
    id: "bath-heading",
    section: "bathroom-reality",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Bathroom Reality 🚿"],
    layouts: { mobile: L(50, 10, 1, 0), desktop: L(50, 12, 1, 0) },
  }),
  el({
    id: "bath-note-1",
    section: "bathroom-reality",
    kind: "card",
    shape: "sticky",
    background: "blue",
    emoji: "⏰",
    lines: ["avoid peak hours", "NOPE HOURS: 7-8:30am"],
    specialLine: 1,
    layouts: { mobile: L(50, 35, 1, -4), desktop: L(22, 50, 1, -4) },
  }),
  el({
    id: "bath-note-2",
    section: "bathroom-reality",
    kind: "card",
    shape: "sticky",
    background: "lavender",
    emoji: "🪣",
    lines: ["carry slippers + bucket"],
    layouts: { mobile: L(50, 62, 1, 5), desktop: L(50, 45, 1, 5) },
  }),
  el({
    id: "bath-note-3",
    section: "bathroom-reality",
    kind: "card",
    shape: "sticky",
    background: "pink",
    emoji: "🧴",
    lines: ["portable toiletry kit"],
    layouts: { mobile: L(50, 85, 1, -2), desktop: L(78, 50, 1, -2) },
  }),

  // ---------- 5. FOOD SURVIVAL ----------
  el({
    id: "food-heading",
    section: "food-survival",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Food Survival 🍜"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "food-polaroid-1",
    section: "food-survival",
    kind: "card",
    shape: "polaroid",
    src: STICKER("midnight-maggi"),
    lines: ["instant noodles"],
    layouts: { mobile: L(25, 30, 1, 4), desktop: L(22, 45, 1, 4) },
  }),
  el({
    id: "food-polaroid-2",
    section: "food-survival",
    kind: "card",
    shape: "polaroid",
    src: STICKER("cookies"),
    lines: ["snack stash"],
    layouts: { mobile: L(75, 40, 1, -6), desktop: L(50, 40, 1, -6) },
  }),
  el({
    id: "food-polaroid-3",
    section: "food-survival",
    kind: "card",
    shape: "polaroid",
    emoji: "🍫",
    lines: ["don't skip meals"],
    layouts: { mobile: L(25, 60, 1, 2), desktop: L(78, 45, 1, 2) },
  }),
  el({
    id: "food-quote",
    section: "food-survival",
    kind: "card",
    shape: "quote",
    background: "none",
    lines: ["energy = mood. eat properly, bestie."],
    highlight: { line: 0, substring: "energy = mood.", color: "#fff3b0" },
    layouts: { mobile: L(50, 88, 1, 1), desktop: L(50, 85, 1, 1) },
  }),

  // ---------- 6. ROOMMATE VIBES ----------
  el({
    id: "mate-heading",
    section: "roommate-vibes",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Roommate Vibes 👯"],
    layouts: { mobile: L(50, 8, 1, 0), desktop: L(50, 10, 1, 0) },
  }),
  el({
    id: "mate-sticker-1",
    section: "roommate-vibes",
    kind: "image",
    src: STICKER("cat-headphones-bubblegum"),
    alt: "cat with headphones sticker",
    layouts: { mobile: L(12, 20, 1, 0), desktop: L(8, 25, 1.2, 0) },
  }),
  el({
    id: "mate-sticker-2",
    section: "roommate-vibes",
    kind: "image",
    src: STICKER("bow-2"),
    alt: "bow sticker",
    layouts: { mobile: L(88, 20, 1, 0), desktop: L(92, 25, 1.2, 0) },
  }),
  el({
    id: "mate-bubble-1",
    section: "roommate-vibes",
    kind: "card",
    shape: "bubble-left",
    background: "blue",
    lines: ["respect > friendship, always 🤝"],
    layouts: { mobile: L(38, 42, 1, -2), desktop: L(25, 45, 1, -2) },
  }),
  el({
    id: "mate-bubble-2",
    section: "roommate-vibes",
    kind: "card",
    shape: "bubble-right",
    background: "pink",
    lines: ["set boundaries early 🚪"],
    layouts: { mobile: L(62, 62, 1, 3), desktop: L(50, 60, 1, 3) },
  }),
  el({
    id: "mate-bubble-3",
    section: "roommate-vibes",
    kind: "card",
    shape: "bubble-left",
    background: "lavender",
    lines: ["communicate clearly, not passive-aggressively 💬"],
    layouts: { mobile: L(38, 82, 1, -1), desktop: L(75, 45, 1, -1) },
  }),

  // ---------- 7. UNDERRATED ESSENTIALS ----------
  el({
    id: "ess-heading",
    section: "underrated-essentials",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Underrated Essentials 🎒"],
    layouts: { mobile: L(50, 10, 0.8, 0), desktop: L(50, 12, 1, 0) },
  }),
  el({
    id: "ess-card-1",
    section: "underrated-essentials",
    kind: "card",
    shape: "torn",
    emoji: "🧵",
    lines: ["sewing kit"],
    layouts: { mobile: L(25, 25, 1, -4), desktop: L(10, 55, 1, -4) },
  }),
  el({
    id: "ess-card-2",
    section: "underrated-essentials",
    kind: "card",
    shape: "torn",
    emoji: "💊",
    lines: ["medicine kit"],
    layouts: { mobile: L(75, 25, 1, 5), desktop: L(30, 55, 1, 5) },
  }),
  el({
    id: "ess-card-3",
    section: "underrated-essentials",
    kind: "card",
    shape: "torn",
    emoji: "🔒",
    lines: ["locks"],
    layouts: { mobile: L(25, 58, 1, -4), desktop: L(50, 55, 1, -4) },
  }),
  el({
    id: "ess-card-4",
    section: "underrated-essentials",
    kind: "card",
    shape: "torn",
    emoji: "🪞",
    lines: ["mirror"],
    layouts: { mobile: L(75, 58, 1, 5), desktop: L(70, 55, 1, 5) },
  }),
  el({
    id: "ess-card-5",
    section: "underrated-essentials",
    kind: "card",
    shape: "torn",
    emoji: "🧷",
    lines: ["cloth clips"],
    layouts: { mobile: L(50, 88, 1, -4), desktop: L(90, 55, 1, 5) },
  }),

  // ---------- 8. FINAL ----------
  el({
    id: "final-sticker-1",
    section: "final",
    kind: "image",
    src: STICKER("you-matter"),
    alt: "you matter sticker",
    layouts: { mobile: L(14, 16, 1, 0), desktop: L(10, 18, 1.3, 0) },
  }),
  el({
    id: "final-sticker-2",
    section: "final",
    kind: "image",
    src: STICKER("bunny-tulips"),
    alt: "bunny with tulips sticker",
    layouts: { mobile: L(86, 16, 1, 0), desktop: L(90, 18, 1.3, 0) },
  }),
  el({
    id: "final-sticker-3",
    section: "final",
    kind: "image",
    src: STICKER("tulips-bouquet"),
    alt: "tulips bouquet sticker",
    layouts: { mobile: L(14, 86, 1, 0), desktop: L(10, 84, 1.3, 0) },
  }),
  el({
    id: "final-sticker-4",
    section: "final",
    kind: "image",
    src: STICKER("evil-eye"),
    alt: "evil eye sticker",
    layouts: { mobile: L(86, 86, 1, 0), desktop: L(90, 84, 1.3, 0) },
  }),
  el({
    id: "final-quote",
    section: "final",
    kind: "card",
    shape: "quote",
    background: "none",
    lines: ["“Hostel life isn't comfort. It's chaos, independence, and memories you'll never forget.”"],
    highlight: { line: 0, substring: "forget" },
    decoration: "circle",
    layouts: { mobile: L(50, 50, 1, 0), desktop: L(50, 50, 1, 0) },
  }),
];
