import type { CanvasElement, ElementLayout } from "@/features/welcome/canvas-types";
import { guideSectionIndex } from "@/features/guide/guide-sections";

function L(x: number, y: number, scale = 1, rotation = 0): ElementLayout {
  return { x, y, scale, rotation, visible: true, zIndex: 0 };
}

function el(partial: Omit<CanvasElement, "section"> & { section: string }): CanvasElement {
  return { ...partial, section: guideSectionIndex(partial.section) };
}

const STICKER = (slug: string) => `/stickers/${slug}.webp`;

/** The full default arrangement of every draggable unit on the survival guide page,
 * approximating today's live layout. Nothing changes for visitors until an admin edits and
 * saves a layout via the "Guide Screen" admin editor — this seed is the fallback. */
export const DEFAULT_GUIDE_ELEMENTS: CanvasElement[] = [
  // ---------- 0. HERO ----------
  el({
    id: "hero-card",
    section: "hero",
    kind: "card",
    shape: "plain",
    background: "white",
    textStyle: "heading",
    isHero: true,
    lines: ["a survival guide for", "Hostel Survival Guide", "Everything no one tells you before move-in day 💌"],
    ctaLabel: "Start Preparing →",
    href: "#mental-prep",
    layouts: { mobile: L(50, 50, 1, -2), desktop: L(50, 50, 1, -2) },
  }),
  el({
    id: "hero-sticker-camera",
    section: "hero",
    kind: "image",
    src: STICKER("camera"),
    alt: "camera sticker",
    layouts: { mobile: L(14, 14, 1, -8), desktop: L(10, 16, 1.3, -8) },
  }),
  el({
    id: "hero-sticker-bow",
    section: "hero",
    kind: "image",
    src: STICKER("bow"),
    alt: "bow sticker",
    layouts: { mobile: L(86, 12, 1, 10), desktop: L(90, 14, 1.3, 10) },
  }),
  el({
    id: "hero-sticker-evil-eye",
    section: "hero",
    kind: "image",
    src: STICKER("evil-eye"),
    alt: "evil eye sticker",
    layouts: { mobile: L(88, 86, 1, -5), desktop: L(92, 84, 1.3, -5) },
  }),
  el({
    id: "hero-sticker-cherries",
    section: "hero",
    kind: "image",
    src: STICKER("cherries"),
    alt: "cherries sticker",
    layouts: { mobile: L(12, 88, 1, 6), desktop: L(8, 86, 1.3, 6) },
  }),

  // ---------- 1. INTRO ----------
  el({
    id: "intro-text",
    section: "intro",
    kind: "card",
    shape: "plain",
    background: "none",
    fontSize: "lg",
    bold: false,
    lines: [
      "Moving to hostel for the first time is exciting and a little overwhelming — new room, new people, zero idea where anything is. This guide won't make it perfect, but it'll help you actually survive the first few weeks and, honestly, start enjoying it.",
    ],
    layouts: { mobile: L(50, 50, 1, 0), desktop: L(50, 50, 1, 0) },
  }),

  // ---------- 2. MENTAL PREP ----------
  el({
    id: "mp-heading",
    section: "mental-prep",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Get your head right 💭"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "mp-note-1",
    section: "mental-prep",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    lines: ["The first week feels awkward", "That's completely normal. Everyone's faking confidence on day one — you're not behind."],
    layouts: { mobile: L(50, 26, 1, -6), desktop: L(22, 42, 1, -6) },
  }),
  el({
    id: "mp-note-2",
    section: "mental-prep",
    kind: "card",
    shape: "sticky",
    background: "pink",
    lines: ["Homesickness hits randomly", "Usually around day 4-5, out of nowhere. It passes faster than it feels like it will."],
    layouts: { mobile: L(50, 48, 1, 4), desktop: L(50, 36, 1, 4) },
  }),
  el({
    id: "mp-note-3",
    section: "mental-prep",
    kind: "card",
    shape: "sticky",
    background: "blue",
    lines: ["Don't isolate yourself", "Keep your door open (literally) the first week — the awkward hallway hi's become your first friendships 🚪"],
    layouts: { mobile: L(50, 70, 1, -3), desktop: L(78, 42, 1, -3) },
  }),
  el({
    id: "mp-image",
    section: "mental-prep",
    kind: "image",
    src: STICKER("bandaid-everything-okay"),
    alt: "Everything will be okay sticker",
    layouts: { mobile: L(50, 92, 1, -1.5), desktop: L(50, 85, 1, -1.5) },
  }),

  // ---------- 3. ROOM SETUP ----------
  el({
    id: "room-heading",
    section: "room-setup",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Room setup strategy 🛏️"],
    layouts: { mobile: L(50, 8, 1, 0), desktop: L(50, 10, 1, 0) },
  }),
  el({
    id: "room-polaroid-1",
    section: "room-setup",
    kind: "card",
    shape: "polaroid",
    emoji: "🔌",
    lines: ["bed near plug ✔"],
    layouts: { mobile: L(25, 30, 1, -5), desktop: L(22, 45, 1, -5) },
  }),
  el({
    id: "room-polaroid-2",
    section: "room-setup",
    kind: "card",
    shape: "polaroid",
    src: STICKER("extension-board"),
    alt: "extension board",
    lines: ["extension board ✔"],
    layouts: { mobile: L(75, 40, 1, 3), desktop: L(50, 40, 1, 3) },
  }),
  el({
    id: "room-polaroid-3",
    section: "room-setup",
    kind: "card",
    shape: "polaroid",
    emoji: "🗂️",
    lines: ["bedside organizer ✔"],
    layouts: { mobile: L(25, 55, 1, -2), desktop: L(78, 45, 1, -2) },
  }),
  el({
    id: "room-quote",
    section: "room-setup",
    kind: "card",
    shape: "quote",
    background: "none",
    lines: ["trust me on the plug point one"],
    highlight: { line: 0, substring: "plug point", color: "#cfeaff" },
    decoration: "arrow",
    layouts: { mobile: L(50, 80, 1, 0), desktop: L(50, 85, 1, 0) },
  }),

  // ---------- 4. ELECTRONICS ----------
  el({
    id: "elec-heading",
    section: "electronics",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Power & gadget hacks 🔌"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "elec-note-1",
    section: "electronics",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    emoji: "⚡",
    lines: ["charging war is real"],
    layouts: { mobile: L(25, 26, 1, 7), desktop: L(22, 42, 1, 7) },
  }),
  el({
    id: "elec-note-2",
    section: "electronics",
    kind: "card",
    shape: "sticky",
    background: "blue",
    emoji: "🔌",
    lines: ["label your chargers"],
    layouts: { mobile: L(75, 26, 1, -8), desktop: L(50, 38, 1, -8) },
  }),
  el({
    id: "elec-note-3",
    section: "electronics",
    kind: "card",
    shape: "sticky",
    background: "pink",
    emoji: "🔋",
    lines: ["power bank is life"],
    layouts: { mobile: L(50, 44, 1, 4), desktop: L(78, 42, 1, 4) },
  }),
  el({
    id: "elec-sticker-1",
    section: "electronics",
    kind: "image",
    src: STICKER("charging-myself"),
    alt: "charging myself sticker",
    layouts: { mobile: L(15, 64, 1, 0), desktop: L(12, 70, 1.2, 0) },
  }),
  el({
    id: "elec-sticker-2",
    section: "electronics",
    kind: "image",
    src: STICKER("extension-board"),
    alt: "extension board sticker",
    layouts: { mobile: L(85, 64, 1, 0), desktop: L(88, 70, 1.2, 0) },
  }),
  el({
    id: "elec-quote",
    section: "electronics",
    kind: "card",
    shape: "quote",
    background: "none",
    lines: ["don't leave gadgets unattended — ever."],
    highlight: { line: 0, substring: "don't leave gadgets unattended", color: "#baffc9" },
    layouts: { mobile: L(50, 82, 1, 0), desktop: L(50, 85, 1, 0) },
  }),

  // ---------- 5. BATHROOM ----------
  el({
    id: "bath-heading",
    section: "bathroom",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Bathroom survival 🚿"],
    layouts: { mobile: L(50, 10, 1, 0), desktop: L(50, 14, 1, 0) },
  }),
  el({
    id: "bath-note-1",
    section: "bathroom",
    kind: "card",
    shape: "sticky",
    background: "blue",
    emoji: "⏰",
    lines: ["avoid peak hours", "NOPE HOURS: 7-8:30am"],
    specialLine: 1,
    layouts: { mobile: L(50, 35, 1, -4), desktop: L(22, 50, 1, -4) },
  }),
  el({
    id: "bath-note-2",
    section: "bathroom",
    kind: "card",
    shape: "sticky",
    background: "lavender",
    emoji: "🪣",
    lines: ["carry slippers + bucket"],
    layouts: { mobile: L(50, 58, 1, 5), desktop: L(50, 45, 1, 5) },
  }),
  el({
    id: "bath-note-3",
    section: "bathroom",
    kind: "card",
    shape: "sticky",
    background: "pink",
    emoji: "🧴",
    lines: ["portable toiletry kit"],
    layouts: { mobile: L(50, 80, 1, -2), desktop: L(78, 50, 1, -2) },
  }),

  // ---------- 6. LAUNDRY ----------
  el({
    id: "laundry-heading",
    section: "laundry",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Clothing & laundry 👕"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "laundry-sticker-1",
    section: "laundry",
    kind: "image",
    src: STICKER("laundry-again"),
    alt: "laundry again sticker",
    layouts: { mobile: L(15, 20, 1, 0), desktop: L(10, 22, 1.2, 0) },
  }),
  el({
    id: "laundry-sticker-2",
    section: "laundry",
    kind: "image",
    src: STICKER("laundry-day"),
    alt: "laundry day sticker",
    layouts: { mobile: L(85, 20, 1, 0), desktop: L(90, 22, 1.2, 0) },
  }),
  el({
    id: "laundry-note-1",
    section: "laundry",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    lines: ["Plan a laundry system", "Pick fixed days. \"Whenever I run out of clothes\" always turns into a crisis."],
    layouts: { mobile: L(50, 42, 1, -5), desktop: L(22, 50, 1, -5) },
  }),
  el({
    id: "laundry-note-2",
    section: "laundry",
    kind: "card",
    shape: "sticky",
    background: "lavender",
    lines: ["Don't pile up clothes", "The chair-pile is a trap. Worn-but-wearable and actually-dirty need separate spots."],
    layouts: { mobile: L(50, 64, 1, 4), desktop: L(50, 55, 1, 4) },
  }),
  el({
    id: "laundry-note-3",
    section: "laundry",
    kind: "card",
    shape: "sticky",
    background: "pink",
    lines: ["Keep quick outfits ready", "One grab-and-go outfit for the mornings you wake up 10 minutes late."],
    layouts: { mobile: L(50, 86, 1, -3), desktop: L(78, 50, 1, -3) },
  }),

  // ---------- 7. FOOD ----------
  el({
    id: "food-heading",
    section: "food",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Food survival 🍜"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "food-polaroid-1",
    section: "food",
    kind: "card",
    shape: "polaroid",
    src: STICKER("midnight-maggi"),
    lines: ["instant noodles"],
    layouts: { mobile: L(25, 28, 1, 4), desktop: L(22, 45, 1, 4) },
  }),
  el({
    id: "food-polaroid-2",
    section: "food",
    kind: "card",
    shape: "polaroid",
    src: STICKER("cookies"),
    lines: ["snack stash"],
    layouts: { mobile: L(75, 38, 1, -6), desktop: L(50, 40, 1, -6) },
  }),
  el({
    id: "food-polaroid-3",
    section: "food",
    kind: "card",
    shape: "polaroid",
    emoji: "🍫",
    lines: ["don't skip meals"],
    layouts: { mobile: L(25, 50, 1, 2), desktop: L(78, 45, 1, 2) },
  }),
  el({
    id: "food-sticker-1",
    section: "food",
    kind: "image",
    src: STICKER("maggi-therapy"),
    alt: "maggi therapy sticker",
    layouts: { mobile: L(15, 66, 1, 0), desktop: L(12, 68, 1.2, 0) },
  }),
  el({
    id: "food-sticker-2",
    section: "food",
    kind: "image",
    src: STICKER("mess-food-survival-food"),
    alt: "mess food survival food sticker",
    layouts: { mobile: L(85, 66, 1, 0), desktop: L(88, 68, 1.2, 0) },
  }),
  el({
    id: "food-quote",
    section: "food",
    kind: "card",
    shape: "quote",
    background: "none",
    lines: ["energy = mood. eat properly, bestie."],
    highlight: { line: 0, substring: "energy = mood.", color: "#fff3b0" },
    layouts: { mobile: L(50, 84, 1, 1), desktop: L(50, 85, 1, 1) },
  }),

  // ---------- 8. ROOMMATES ----------
  el({
    id: "mate-heading",
    section: "roommates",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Roommate dynamics 👯"],
    layouts: { mobile: L(50, 8, 1, 0), desktop: L(50, 10, 1, 0) },
  }),
  el({
    id: "mate-sticker-1",
    section: "roommates",
    kind: "image",
    src: STICKER("cat-headphones-bubblegum"),
    alt: "cat with headphones sticker",
    layouts: { mobile: L(15, 20, 1, 0), desktop: L(10, 22, 1.2, 0) },
  }),
  el({
    id: "mate-sticker-2",
    section: "roommates",
    kind: "image",
    src: STICKER("bow-2"),
    alt: "bow sticker",
    layouts: { mobile: L(85, 20, 1, 0), desktop: L(90, 22, 1.2, 0) },
  }),
  el({
    id: "mate-bubble-1",
    section: "roommates",
    kind: "card",
    shape: "bubble-left",
    background: "blue",
    lines: ["respect > friendship, always 🤝"],
    layouts: { mobile: L(38, 42, 1, -2), desktop: L(25, 45, 1, -2) },
  }),
  el({
    id: "mate-bubble-2",
    section: "roommates",
    kind: "card",
    shape: "bubble-right",
    background: "pink",
    lines: ["set boundaries early 🚪"],
    layouts: { mobile: L(62, 60, 1, 3), desktop: L(50, 58, 1, 3) },
  }),
  el({
    id: "mate-bubble-3",
    section: "roommates",
    kind: "card",
    shape: "bubble-left",
    background: "lavender",
    lines: ["communicate clearly, not passive-aggressively 💬"],
    layouts: { mobile: L(38, 78, 1, -1), desktop: L(75, 45, 1, -1) },
  }),

  // ---------- 9. HYGIENE ----------
  el({
    id: "hygiene-heading",
    section: "hygiene",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Weekly reset 🧺"],
    layouts: { mobile: L(50, 8, 1, 0), desktop: L(50, 10, 1, 0) },
  }),
  el({
    id: "hygiene-sticker-1",
    section: "hygiene",
    kind: "image",
    src: STICKER("small-steps-every-day"),
    alt: "small steps every day sticker",
    layouts: { mobile: L(15, 22, 1, 0), desktop: L(10, 24, 1.2, 0) },
  }),
  el({
    id: "hygiene-sticker-2",
    section: "hygiene",
    kind: "image",
    src: STICKER("potted-plant"),
    alt: "potted plant sticker",
    layouts: { mobile: L(85, 22, 1, 0), desktop: L(90, 24, 1.2, 0) },
  }),
  el({
    id: "hygiene-item-1",
    section: "hygiene",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    lines: ["✔ Change bedsheets"],
    layouts: { mobile: L(50, 42, 1, -3), desktop: L(25, 50, 1, -3) },
  }),
  el({
    id: "hygiene-item-2",
    section: "hygiene",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    lines: ["✔ Clean your space"],
    layouts: { mobile: L(50, 60, 1, 3), desktop: L(50, 50, 1, 3) },
  }),
  el({
    id: "hygiene-item-3",
    section: "hygiene",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    lines: ["✔ Organize your desk"],
    layouts: { mobile: L(50, 78, 1, -2), desktop: L(75, 50, 1, -2) },
  }),

  // ---------- 10. SAFETY ----------
  el({
    id: "safety-heading",
    section: "safety",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Safety first 🔒"],
    layouts: { mobile: L(50, 8, 1, 0), desktop: L(50, 10, 1, 0) },
  }),
  el({
    id: "safety-note-1",
    section: "safety",
    kind: "card",
    shape: "sticky",
    background: "lavender",
    lines: ["Lock your belongings", "Even around people you trust. It protects the friendship, not just your stuff."],
    layouts: { mobile: L(50, 28, 1, -5), desktop: L(22, 42, 1, -5) },
  }),
  el({
    id: "safety-note-2",
    section: "safety",
    kind: "card",
    shape: "sticky",
    background: "pink",
    lines: ["Don't overshare", "New friends are great — your schedule, valuables, and family details can wait."],
    layouts: { mobile: L(50, 48, 1, 4), desktop: L(50, 38, 1, 4) },
  }),
  el({
    id: "safety-note-3",
    section: "safety",
    kind: "card",
    shape: "sticky",
    background: "blue",
    lines: ["Keep emergency contacts handy", "Warden, parents, a trusted senior — saved and easy to reach, not buried in chats."],
    layouts: { mobile: L(50, 68, 1, -3), desktop: L(78, 42, 1, -3) },
  }),
  el({
    id: "safety-cta",
    section: "safety",
    kind: "card",
    shape: "plain",
    background: "none",
    ctaLabel: "Add your emergency contacts in the app →",
    href: "/contacts",
    layouts: { mobile: L(50, 86, 1, 0), desktop: L(50, 80, 1, 0) },
  }),

  // ---------- 11. ROUTINE ----------
  el({
    id: "routine-heading",
    section: "routine",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["A minimal daily routine ⏰"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "routine-sticker-1",
    section: "routine",
    kind: "image",
    src: STICKER("alarm-clock"),
    alt: "alarm clock sticker",
    layouts: { mobile: L(14, 20, 1, 0), desktop: L(10, 22, 1.2, 0) },
  }),
  el({
    id: "routine-sticker-2",
    section: "routine",
    kind: "image",
    src: STICKER("sleep-is-overrated"),
    alt: "sleep is overrated sticker",
    layouts: { mobile: L(50, 18, 1, 0), desktop: L(50, 20, 1.2, 0) },
  }),
  el({
    id: "routine-sticker-3",
    section: "routine",
    kind: "image",
    src: STICKER("sleepy-moon"),
    alt: "sleepy moon sticker",
    layouts: { mobile: L(86, 20, 1, 0), desktop: L(90, 22, 1.2, 0) },
  }),
  el({
    id: "routine-note-1",
    section: "routine",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    lines: ["Fixed wake-up time", "Even on off days. It's the one habit that keeps everything else on track."],
    layouts: { mobile: L(50, 42, 1, -4), desktop: L(22, 50, 1, -4) },
  }),
  el({
    id: "routine-note-2",
    section: "routine",
    kind: "card",
    shape: "sticky",
    background: "blue",
    lines: ["One study/work block", "Doesn't need to be long — just protected, distraction-free time."],
    layouts: { mobile: L(50, 62, 1, 5), desktop: L(50, 42, 1, 5) },
  }),
  el({
    id: "routine-note-3",
    section: "routine",
    kind: "card",
    shape: "sticky",
    background: "pink",
    lines: ["Actual chill time", "Not scrolling-in-bed chill. Something that genuinely resets you."],
    layouts: { mobile: L(50, 82, 1, -2), desktop: L(78, 50, 1, -2) },
  }),

  // ---------- 12. SOCIAL ----------
  el({
    id: "social-heading",
    section: "social",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Social life 🎉"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "social-sticker-1",
    section: "social",
    kind: "image",
    src: STICKER("cow-boba"),
    alt: "cow with boba sticker",
    layouts: { mobile: L(14, 20, 1, 0), desktop: L(10, 22, 1.2, 0) },
  }),
  el({
    id: "social-sticker-2",
    section: "social",
    kind: "image",
    src: STICKER("choose-happy"),
    alt: "choose happy sticker",
    layouts: { mobile: L(50, 18, 1, 0), desktop: L(50, 20, 1.2, 0) },
  }),
  el({
    id: "social-sticker-3",
    section: "social",
    kind: "image",
    src: STICKER("room-518-legends"),
    alt: "room 518 legends sticker",
    layouts: { mobile: L(86, 20, 1, 0), desktop: L(90, 22, 1.2, 0) },
  }),
  el({
    id: "social-note-1",
    section: "social",
    kind: "card",
    shape: "sticky",
    background: "pink",
    lines: ["Find 2-3 real people", "Not a big group — just a few people you can actually be yourself around."],
    layouts: { mobile: L(50, 42, 1, -4), desktop: L(22, 50, 1, -4) },
  }),
  el({
    id: "social-note-2",
    section: "social",
    kind: "card",
    shape: "sticky",
    background: "lavender",
    lines: ["Avoid toxic groups", "If a group makes you anxious more than happy, it's not your people."],
    layouts: { mobile: L(50, 62, 1, 5), desktop: L(50, 42, 1, 5) },
  }),
  el({
    id: "social-note-3",
    section: "social",
    kind: "card",
    shape: "sticky",
    background: "blue",
    lines: ["Don't force friendships", "Some people click in week one, others in month three. Both are fine."],
    layouts: { mobile: L(50, 82, 1, -3), desktop: L(78, 50, 1, -3) },
  }),

  // ---------- 13. MONEY ----------
  el({
    id: "money-heading",
    section: "money",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Money management 💸"],
    layouts: { mobile: L(50, 7, 1, 0), desktop: L(50, 9, 1, 0) },
  }),
  el({
    id: "money-sticker-1",
    section: "money",
    kind: "image",
    src: STICKER("budget-zero-stories-hero"),
    alt: "budget zero stories hero sticker",
    layouts: { mobile: L(15, 20, 1, 0), desktop: L(10, 22, 1.2, 0) },
  }),
  el({
    id: "money-sticker-2",
    section: "money",
    kind: "image",
    src: STICKER("paise-khatam-emotion-khatam"),
    alt: "paise khatam emotion khatam sticker",
    layouts: { mobile: L(85, 20, 1, 0), desktop: L(90, 22, 1.2, 0) },
  }),
  el({
    id: "money-note-1",
    section: "money",
    kind: "card",
    shape: "sticky",
    background: "yellow",
    lines: ["Track your weekly spend", "Even a rough estimate beats finding out you're broke on day 20."],
    layouts: { mobile: L(50, 40, 1, -5), desktop: L(22, 45, 1, -5) },
  }),
  el({
    id: "money-note-2",
    section: "money",
    kind: "card",
    shape: "sticky",
    background: "blue",
    lines: ["Avoid overspending early", "The first two weeks of \"exploring\" add up fast. Pace yourself."],
    layouts: { mobile: L(50, 58, 1, 4), desktop: L(50, 40, 1, 4) },
  }),
  el({
    id: "money-note-3",
    section: "money",
    kind: "card",
    shape: "sticky",
    background: "pink",
    lines: ["Keep emergency cash aside", "Separate from your everyday spending money. Don't touch it unless it's real."],
    layouts: { mobile: L(50, 76, 1, -3), desktop: L(78, 45, 1, -3) },
  }),
  el({
    id: "money-cta",
    section: "money",
    kind: "card",
    shape: "plain",
    background: "none",
    ctaLabel: "Track your spending in the Budget tab →",
    href: "/budget",
    layouts: { mobile: L(50, 90, 1, 0), desktop: L(50, 82, 1, 0) },
  }),

  // ---------- 14. ESSENTIALS ----------
  el({
    id: "ess-heading",
    section: "essentials",
    kind: "card",
    shape: "plain",
    background: "none",
    textStyle: "heading",
    lines: ["Underrated essentials 🎒"],
    layouts: { mobile: L(50, 7, 0.8, 0), desktop: L(50, 10, 1, 0) },
  }),
  el({
    id: "ess-card-1",
    section: "essentials",
    kind: "card",
    shape: "torn",
    emoji: "🧵",
    lines: ["sewing kit"],
    layouts: { mobile: L(20, 26, 1, -4), desktop: L(10, 50, 1, -4) },
  }),
  el({
    id: "ess-card-2",
    section: "essentials",
    kind: "card",
    shape: "torn",
    emoji: "💊",
    lines: ["medicine kit"],
    layouts: { mobile: L(50, 20, 1, 5), desktop: L(30, 45, 1, 5) },
  }),
  el({
    id: "ess-card-3",
    section: "essentials",
    kind: "card",
    shape: "torn",
    emoji: "🔒",
    lines: ["locks"],
    layouts: { mobile: L(80, 26, 1, -4), desktop: L(50, 50, 1, -4) },
  }),
  el({
    id: "ess-card-4",
    section: "essentials",
    kind: "card",
    shape: "torn",
    emoji: "🪞",
    lines: ["mirror"],
    layouts: { mobile: L(35, 46, 1, 5), desktop: L(70, 45, 1, 5) },
  }),
  el({
    id: "ess-card-5",
    section: "essentials",
    kind: "card",
    shape: "torn",
    emoji: "🧷",
    lines: ["cloth clips"],
    layouts: { mobile: L(65, 46, 1, -4), desktop: L(90, 50, 1, 5) },
  }),
  el({
    id: "ess-cta",
    section: "essentials",
    kind: "card",
    shape: "plain",
    background: "none",
    ctaLabel: "These are already in your packing checklist →",
    href: "/checklist",
    layouts: { mobile: L(50, 66, 1, 0), desktop: L(50, 70, 1, 0) },
  }),

  // ---------- 15. FINAL ----------
  el({
    id: "final-sticker-1",
    section: "final",
    kind: "image",
    src: STICKER("you-matter"),
    alt: "you matter sticker",
    layouts: { mobile: L(14, 16, 1, 0), desktop: L(10, 18, 1.3, 0) },
  }),
  el({
    id: "final-sticker-2",
    section: "final",
    kind: "image",
    src: STICKER("bunny-tulips"),
    alt: "bunny with tulips sticker",
    layouts: { mobile: L(86, 16, 1, 0), desktop: L(90, 18, 1.3, 0) },
  }),
  el({
    id: "final-sticker-3",
    section: "final",
    kind: "image",
    src: STICKER("tulips-bouquet"),
    alt: "tulips bouquet sticker",
    layouts: { mobile: L(14, 86, 1, 0), desktop: L(10, 84, 1.3, 0) },
  }),
  el({
    id: "final-sticker-4",
    section: "final",
    kind: "image",
    src: STICKER("hostel-life-best-life"),
    alt: "hostel life best life sticker",
    layouts: { mobile: L(86, 86, 1, 0), desktop: L(90, 84, 1.3, 0) },
  }),
  el({
    id: "final-quote",
    section: "final",
    kind: "card",
    shape: "quote",
    background: "none",
    lines: ["“Hostel life isn't about comfort. It's about growth, independence, and stories you'll never forget.”"],
    highlight: { line: 0, substring: "forget" },
    decoration: "circle",
    ctaLabel: "Start Your Hostel Journey →",
    href: "/checklist",
    layouts: { mobile: L(50, 50, 1, 0), desktop: L(50, 50, 1, 0) },
  }),
];
